(function () {
  var shell = document.getElementById("shell");
  var index = window.SITE_INDEX || { runs: [], latest: "" };
  var snapshots = window.SITE_SNAPSHOTS || {};
  var currentRun = null;
  var role = "manager";
  var page = "Dashboard";
  var engineerTab = "Overview";
  var selectedKb = "";
  var query = "";
  var severity = "All severities";
  var config = "All configurations";
  var pageConfigMap = {};
  var SEV = { critical: 0, high: 1, important: 1, medium: 2, moderate: 2, low: 3 };

  var SCORE_VALUE_LABELS = {
    required: "Required",
    not_required: "Not required",
    breaks_app: "App may stop working",
    may_break_app: "App may break",
    compatible: "Compatible with the app",
    app_will_fail: "App will fail",
    stays_vulnerable: "Configuration stays exposed",
    no_app_impact: "No effect on the app",
    incompatible: "Not compatible"
  };
  var RISK_HINTS = {
    stays_vulnerable: "If we do not install this KB, the configuration stays exposed on that host path.",
    may_break_app: "If we install this KB, the app on main may break.",
    no_app_impact: "If we skip this KB, the app on main does not change.",
    compatible: "If we install this KB, the app on main should still run."
  };
  var SCORE_FIELD_HINTS = {
    required_for_app: "Does the product on main need this KB to keep working?",
    install_risk: "What happens to the app if we put the KB on the configuration?",
    skip_risk: "What happens if we leave the KB off the configuration?",
    compatibility: "Does current main work with these vendor bits?",
    vendor_severity: "Microsoft / FindUpdates severity as C H M L.",
    vendor_likelihood: "KEV is C. High exploitability is H. Unknown is M.",
    vendor_risk: "Combined vendor severity and likelihood.",
    product_severity: "How severe this is for the published exe on this configuration.",
    product_likelihood: "How reachable the issue is on this configuration. Often L when the component is not loaded.",
    product_risk: "Product risk may be L even when vendor risk is C."
  };

  function formatAiUsage(usage) {
    if (!usage || !usage.provider) return "AI usage was not recorded for this run.";
    if (usage.provider === "offline") return "Analysis used offline scripts.";
    var modelBit = usage.model ? ", model " + usage.model : "";
    return "Analysis used " + usage.provider + modelBit + ".";
  }

  function updateFooter(run) {
    var el = document.getElementById("site-footer");
    if (!el) return;
    el.innerHTML = "Generated by <code>scripts/build-pages-site.py</code>. " +
      esc(formatAiUsage(run && run.ai));
  }

  function text(value, fallback) {
    if (value === null || value === undefined || value === "") return fallback || "—";
    return String(value);
  }

  function esc(value) {
    return text(value).replace(/[&<>"]/g, function (ch) {
      return ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[ch];
    });
  }

  function link(href, label) {
    if (!href) return esc(label);
    return '<a href="' + esc(href) + '">' + esc(label) + "</a>";
  }

  function infoTip(text) {
    return '<span class="info-tip" tabindex="0"><span class="info-mark">i</span><span class="tip">' +
      esc(text) + "</span></span>";
  }

  function scoreLabel(value) {
    var raw = String(value || "").trim();
    if (!raw) return "—";
    return SCORE_VALUE_LABELS[raw] || raw.replace(/_/g, " ");
  }

  function scoreRows(cluster) {
    function hint(field, value) {
      var key = String(value || "").trim();
      if (RISK_HINTS[key]) return RISK_HINTS[key];
      return SCORE_FIELD_HINTS[field];
    }
    var rows = [
      ["Required for app", scoreLabel(cluster && cluster.required_for_app), hint("required_for_app", cluster && cluster.required_for_app)],
      ["If we install", scoreLabel(cluster && cluster.install_risk), hint("install_risk", cluster && cluster.install_risk)],
      ["If we skip", scoreLabel(cluster && cluster.skip_risk), hint("skip_risk", cluster && cluster.skip_risk)],
      ["Compatibility", scoreLabel(cluster && cluster.compatibility), hint("compatibility", cluster && cluster.compatibility)]
    ];
    [
      ["Vendor severity", "vendor_severity"],
      ["Vendor likelihood", "vendor_likelihood"],
      ["Vendor risk", "vendor_risk"],
      ["Product severity", "product_severity"],
      ["Product likelihood", "product_likelihood"],
      ["Product risk", "product_risk"]
    ].forEach(function (item) {
      rows.push([item[0], (cluster && cluster[item[1]]) || "NA", SCORE_FIELD_HINTS[item[1]]]);
    });
    return rows;
  }

  function scoreList(cluster) {
    var html = '<dl class="score-list">';
    scoreRows(cluster).forEach(function (row) {
      html += "<div><span class=\"info-slot\">" + infoTip(row[2]) +
        "</span><dt>" + esc(row[0]) + "</dt><dd>" + esc(row[1]) + "</dd></div>";
    });
    return html + "</dl>";
  }

  function realClusters(run) {
    return (run && run.clusters || []).filter(function (item) {
      return item && item.cluster_key !== "ai-usage" && item.title !== "ai-usage";
    });
  }

  function configNameMap(packages) {
    var seen = {};
    (packages || []).forEach(function (item) {
      (item.stations || []).forEach(function (raw) {
        var name = String(raw || "").trim();
        if (name) seen[name] = 1;
      });
    });
    var map = {};
    Object.keys(seen).sort().forEach(function (name, i) {
      map[name] = "Configurations" + (i + 1);
    });
    return map;
  }

  function configLabel(name) {
    var key = String(name || "").trim();
    return pageConfigMap[key] || key;
  }

  function labeledStations(ids) {
    return (ids || []).map(function (id) { return configLabel(id); }).join(", ");
  }

  function configNames() {
    return Object.keys(pageConfigMap).sort().map(function (id) { return pageConfigMap[id]; });
  }

  function packages(run) {
    return ((run && run.bundle) || {}).packages || [];
  }

  function uniqueKbMap(list) {
    var map = {};
    (list || []).forEach(function (item, index) {
      var kb = String(item.kb || "").trim() || ("row-" + index);
      if (!map[kb]) {
        map[kb] = item;
        return;
      }
      if (item.include_in_deploy && !map[kb].include_in_deploy) map[kb] = item;
    });
    return map;
  }

  function uniquePackages(run) {
    var map = uniqueKbMap(packages(run));
    return Object.keys(map).map(function (kb) { return map[kb]; });
  }

  function uniqueCounts(run) {
    var rec = 0;
    var hold = 0;
    uniquePackages(run).forEach(function (item) {
      if (item.include_in_deploy) rec += 1;
      else hold += 1;
    });
    return { applicable: rec + hold, recommended: rec, held: hold };
  }

  function configUpdateCounts(list) {
    var recommended = {};
    var ignored = {};
    (list || []).forEach(function (item, index) {
      var kb = String(item.kb || ("row-" + index));
      var names = item.stations || [];
      var bucket = item.include_in_deploy ? recommended : ignored;
      names.forEach(function (raw) {
        var name = String(raw || "").trim();
        if (!name) return;
        if (!bucket[name]) bucket[name] = {};
        bucket[name][kb] = 1;
      });
    });
    var names = Object.keys(recommended).concat(Object.keys(ignored)).filter(function (name, i, all) {
      return all.indexOf(name) === i;
    }).sort();
    return names.map(function (name) {
      return {
        name: name,
        recommended: Object.keys(recommended[name] || {}).length,
        ignored: Object.keys(ignored[name] || {}).length
      };
    });
  }

  function configChartCaption(rows, runId, historyN) {
    var recommended = 0;
    var ignored = 0;
    (rows || []).forEach(function (row) {
      recommended += Number(row.recommended || 0);
      ignored += Number(row.ignored || 0);
    });
    var runBit = runId ? "This run (" + runId + ")" : "This run";
    var line = runBit + ": " + ignored + " applicable for our platform · " +
      recommended + " recommended to install across " + (rows || []).length +
      " configurations.";
    if (!historyN || historyN < 2) return line + " History will grow with later runs.";
    return line + " " + historyN + " runs in the last 90 days.";
  }

  function configBars(rows) {
    var list = rows || [];
    if (!list.length) {
      return '<p class="empty">No configuration counts on this run.</p>';
    }
    var n = list.length;
    var w = Math.max(640, n * 90);
    var h = 220;
    var padL = 36;
    var padR = 16;
    var padT = 24;
    var padB = 56;
    var innerW = w - padL - padR;
    var innerH = h - padT - padB;
    var groupW = innerW / n;
    var max = 1;
    list.forEach(function (row) {
      if (row.recommended > max) max = row.recommended;
      if (row.ignored > max) max = row.ignored;
    });
    var barW = Math.min(18, groupW / 2 - 6);
    var svg = '<svg viewBox="0 0 ' + w + " " + h + '" class="chart">';
    svg += '<text x="0" y="' + (padT + 4) + '" class="chart-lab">' + max + "</text>";
    svg += '<text x="0" y="' + (padT + innerH + 4) + '" class="chart-lab">0</text>';
    list.forEach(function (row, i) {
      var cx = padL + i * groupW + groupW / 2;
      var recH = row.recommended / max * innerH;
      var ignH = row.ignored / max * innerH;
      var ignX = cx - barW - 2;
      var recX = cx + 2;
      if (ignH > 0) {
        svg += '<rect x="' + ignX + '" y="' + (padT + innerH - ignH) + '" width="' + barW +
          '" height="' + ignH + '" fill="#0b57b8"/>';
      }
      if (recH > 0) {
        svg += '<rect x="' + recX + '" y="' + (padT + innerH - recH) + '" width="' + barW +
          '" height="' + recH + '" fill="#ef3e4e"/>';
      }
      svg += '<text x="' + (ignX + barW / 2) + '" y="' + (padT + innerH - ignH - 4) +
        '" text-anchor="middle" class="chart-n">' + row.ignored + "</text>";
      svg += '<text x="' + (recX + barW / 2) + '" y="' + (padT + innerH - recH - 4) +
        '" text-anchor="middle" class="chart-n">' + row.recommended + "</text>";
      svg += '<text x="' + cx + '" y="' + (h - 20) + '" text-anchor="middle" class="chart-lab">' +
        esc(configLabel(row.name)) + "</text>";
    });
    return svg + "</svg>";
  }

  function psirtMatrix(run) {
    var matrix = (run && run.psirt_matrix) || {};
    var columns = matrix.columns || [];
    var rows = matrix.rows || [];
    if (!columns.length || !rows.length) return "";
    var parts = ['<div class="matrix-wrap"><table><thead><tr><th>KB</th>'];
    columns.forEach(function (name) { parts.push("<th>" + esc(name) + "</th>"); });
    parts.push("</tr></thead><tbody>");
    rows.forEach(function (row) {
      parts.push("<tr><td>" + esc(row.kb) + "</td>");
      (row.cells || []).forEach(function (cell) { parts.push("<td>" + esc(cell) + "</td>"); });
      parts.push("</tr>");
    });
    parts.push("</tbody></table></div>");
    return parts.join("");
  }

  function glance(run) {
    var rows = configUpdateCounts(packages(run));
    var historyN = allSnapshots().length;
    var parts = [];
    parts.push('<p class="chart-cap">' + esc(configChartCaption(rows, run.run_id, historyN)) + "</p>");
    parts.push('<p class="chart-legend">Blue applicable for our platform · red recommended to install</p>');
    parts.push(configBars(rows));
    return parts.join("");
  }

  function allSnapshots() {
    var list = [];
    Object.keys(snapshots).forEach(function (id) { list.push(snapshots[id]); });
    list.sort(function (a, b) { return String(a.created_at || "").localeCompare(String(b.created_at || "")); });
    return list;
  }

  function clustersForKb(run, kb) {
    var needle = String(kb || "").trim();
    var pkg = uniqueKbMap(packages(run))[needle];
    var stations = (pkg && pkg.stations) || [];
    return realClusters(run).filter(function (item) {
      var pkgs = item.packages || [];
      if (pkgs.length && pkgs.indexOf(needle) !== -1) return true;
      if (String(item.title || "").indexOf(needle) !== -1) return true;
      if (!pkgs.length && pkg && stations.indexOf(item.device_id) !== -1) return true;
      return false;
    });
  }

  function lettersForKb(run, kb) {
    var list = clustersForKb(run, kb);
    var item = list[0] || {};
    return {
      vendor: item.vendor_risk || "NA",
      product: item.product_risk || "NA",
      vendor_severity: item.vendor_severity || "NA",
      vendor_likelihood: item.vendor_likelihood || "NA",
      vendor_risk: item.vendor_risk || "NA",
      product_severity: item.product_severity || "NA",
      product_likelihood: item.product_likelihood || "NA",
      product_risk: item.product_risk || "NA",
      cluster: item
    };
  }

  function badgeSev(value) {
    var raw = String(value || "").toLowerCase();
    var cls = "low";
    if (raw === "critical") cls = "critical";
    else if (raw === "high" || raw === "important") cls = "high";
    else if (raw === "medium" || raw === "moderate") cls = "medium";
    return '<span class="badge ' + cls + '">' + esc(value || "—") + "</span>";
  }

  function recBadge(pkg) {
    return pkg.include_in_deploy
      ? '<span class="badge install">Install</span>'
      : '<span class="badge hold">Hold</span>';
  }

  function recStatus(pkg) {
    return pkg.include_in_deploy
      ? '<span class="status install">Install</span>'
      : '<span class="status hold">Hold</span>';
  }

  function risk(letter) {
    var t = String(letter || "NA");
    return '<span class="risk ' + esc(t) + '">' + esc(t) + "</span>";
  }

  function panel(title, body) {
    return '<section class="panel"><div class="panelHead"><h2>' + title + "</h2></div>" + body + "</section>";
  }

  function infoRows(rows) {
    return '<div class="info">' + rows.map(function (row) {
      return "<div><span>" + row[0] + "</span><b>" + row[1] + "</b></div>";
    }).join("") + "</div>";
  }

  function severityDonut(run) {
    var buckets = { Critical: 0, High: 0, Medium: 0, Low: 0 };
    uniquePackages(run).forEach(function (item) {
      var raw = String(item.severity || "").toLowerCase();
      if (raw === "critical") buckets.Critical += 1;
      else if (raw === "high" || raw === "important") buckets.High += 1;
      else if (raw === "medium" || raw === "moderate") buckets.Medium += 1;
      else buckets.Low += 1;
    });
    var labels = ["Critical", "High", "Medium", "Low"];
    var vals = labels.map(function (name) { return buckets[name]; });
    var total = vals.reduce(function (sum, n) { return sum + n; }, 0);
    if (!total) return '<p class="empty">No severity counts on this run.</p>';
    var colors = ["#0b57b8", "#3186e5", "#8abcf2", "#cbd5e1"];
    var start = 0;
    var arcs = "";
    vals.forEach(function (v, i) {
      if (!v) return;
      var a = v / total * 360;
      var x1 = 65 + 50 * Math.cos((start - 90) * Math.PI / 180);
      var y1 = 65 + 50 * Math.sin((start - 90) * Math.PI / 180);
      var x2 = 65 + 50 * Math.cos((start + a - 90) * Math.PI / 180);
      var y2 = 65 + 50 * Math.sin((start + a - 90) * Math.PI / 180);
      arcs += '<path d="M 65 65 L ' + x1 + " " + y1 + " A 50 50 0 " + (a > 180 ? 1 : 0) +
        " 1 " + x2 + " " + y2 + ' Z" fill="' + colors[i] + '"></path>';
      start += a;
    });
    return '<div class="donutWrap"><svg class="donut" viewBox="0 0 130 150">' + arcs +
      '<circle cx="65" cy="65" r="31" fill="white"></circle>' +
      '<text x="65" y="64" text-anchor="middle" font-size="22" font-weight="800" fill="#18365e">' +
      total + '</text><text x="65" y="80" text-anchor="middle" font-size="9" fill="#71849c">Applicable</text></svg>' +
      '<div class="legend">' + labels.map(function (label, i) {
        return "<div><i style=\"background:" + colors[i] + '"></i><span>' + label +
          "</span><b>" + vals[i] + " (" + Math.round(vals[i] / total * 100) + "%)</b></div>";
      }).join("") + "</div></div>";
  }

  function pipeline(run) {
    var pkgN = uniquePackages(run).length;
    var clusterN = realClusters(run).length;
    var tests = (run && run.tests) || {};
    var testBit = tests.outcome ? String(tests.outcome) + " " + text(tests.passed, "0") + "/" + text(tests.total, "0") : "not in this snapshot";
    var bundleId = ((run && run.bundle) || {}).bundle_id || "not in this snapshot";
    var rows = [
      ["Packages", pkgN, Math.max(pkgN, 1)],
      ["Impact clusters", clusterN, Math.max(pkgN, clusterN, 1)],
      ["Host Application tests", tests.outcome ? Number(tests.passed || 0) : 0, Math.max(Number(tests.total || 0), 1)],
      ["Bundle", bundleId && bundleId !== "not in this snapshot" ? 1 : 0, 1]
    ];
    return '<div class="pipelineRows">' + rows.map(function (row) {
      var pct = Math.round(row[1] / row[2] * 100);
      return '<div class="pipe"><span>' + row[0] + "</span><div><i style=\"width:" + pct +
        '%"></i></div><b>' + esc(String(row[0] === "Bundle" ? (bundleId === "not in this snapshot" ? "—" : "yes") : (row[0] === "Host Application tests" ? testBit : row[1]))) + "</b></div>";
    }).join("") + "</div>";
  }

  function trendChart() {
    var points = allSnapshots().map(function (item) {
      var counts = uniqueCounts(item);
      return {
        run_id: item.run_id,
        created_at: item.created_at,
        recommended: counts.recommended,
        held: counts.held
      };
    });
    if (!points.length) return '<p class="empty">History will grow with later runs.</p>';
    var w = 700;
    var h = 180;
    var padL = 28;
    var padR = 12;
    var padT = 16;
    var padB = 24;
    var innerW = w - padL - padR;
    var innerH = h - padT - padB;
    var max = 1;
    points.forEach(function (p) {
      if (p.recommended > max) max = p.recommended;
      if (p.held > max) max = p.held;
    });
    function xAt(i) {
      if (points.length === 1) return padL + innerW / 2;
      return padL + i * innerW / (points.length - 1);
    }
    function yAt(v) { return padT + innerH - (Number(v) / max) * innerH; }
    function path(key) {
      return points.map(function (p, i) {
        return (i ? "L" : "M") + xAt(i) + " " + yAt(p[key]);
      }).join(" ");
    }
    var first = String(points[0].created_at || "").slice(0, 10);
    var last = String(points[points.length - 1].created_at || "").slice(0, 10);
    return '<div class="trend"><svg viewBox="0 0 ' + w + " " + h +
      '" preserveAspectRatio="none"><path d="' + path("held") +
      '" fill="none" stroke="#0b57b8" stroke-width="4"/><path d="' + path("recommended") +
      '" fill="none" stroke="#ef3e4e" stroke-width="3"/></svg><div class="axis"><span>' +
      esc(first) + "</span><span>" + esc(last) + "</span></div></div>";
  }

  function filteredPackages(run) {
    return uniquePackages(run).filter(function (pkg) {
      var hay = (pkg.kb + " " + pkg.title).toLowerCase();
      if (query && hay.indexOf(query.toLowerCase()) === -1) return false;
      if (severity !== "All severities") {
        if (String(pkg.severity || "").toUpperCase() !== severity) return false;
      }
      if (config !== "All configurations") {
        var labels = labeledStations(pkg.stations);
        if (labels.indexOf(config) === -1) return false;
      }
      return true;
    });
  }

  function patchTable(run, rows) {
    if (!rows.length) return '<p class="empty">No patches match the selected filters.</p>';
    var html = '<div style="overflow:auto"><table><thead><tr><th>KB</th><th>Title</th><th>Severity</th><th>Recommendation</th><th>Configurations</th><th>CVEs</th><th>Vendor</th><th>Product</th><th>Status</th><th></th></tr></thead><tbody>';
    rows.forEach(function (pkg) {
      var letters = lettersForKb(run, pkg.kb);
      html += "<tr><td><button class=\"link\" data-open-kb=\"" + esc(pkg.kb) + "\">" + esc(pkg.kb) +
        "</button></td><td>" + esc(pkg.title) + "</td><td>" + badgeSev(pkg.severity) +
        "</td><td>" + recBadge(pkg) + "</td><td>" + esc(labeledStations(pkg.stations)) +
        "</td><td>" + esc((pkg.cve_ids || []).join(", ") || "—") +
        "</td><td>" + risk(letters.vendor) + "</td><td>" + risk(letters.product) +
        "</td><td>" + recStatus(pkg) + "</td><td><button class=\"view\" data-open-kb=\"" +
        esc(pkg.kb) + "\">View</button></td></tr>";
    });
    return html + "</tbody></table></div>";
  }

  function filtersBar(run) {
    var names = configNames();
    var sevOpts = ["All severities", "CRITICAL", "HIGH", "MEDIUM", "LOW"];
    return '<div class="filters"><div class="search"><input id="kb-search" placeholder="Search KB or title" value="' +
      esc(query) + '"></div><select id="config-filter"><option>All configurations</option>' +
      names.map(function (name) {
        return "<option" + (config === name ? " selected" : "") + ">" + esc(name) + "</option>";
      }).join("") +
      '</select><select id="severity-filter">' +
      sevOpts.map(function (name) {
        return "<option" + (severity === name ? " selected" : "") + ">" + esc(name) + "</option>";
      }).join("") +
      "</select></div>";
  }

  function kpi(icon, value, label, note, cls) {
    return '<div class="kpi ' + (cls || "") + '"><div class="kpiIcon">' + icon +
      "</div><div><strong>" + esc(String(value)) + "</strong><b>" + esc(label) +
      "</b><span>" + esc(note) + "</span></div></div>";
  }

  function managerDashboard(run) {
    var counts = uniqueCounts(run);
    var historyN = allSnapshots().length;
    var rows = filteredPackages(run);
    return '<div class="pageHead"><div><h1>Patch Management Overview</h1>' +
      "<p>Executive summary of Microsoft Windows updates for Host Application configurations</p></div>" +
      '<div class="period">Last 90 days</div></div>' +
      '<p class="banner">Advisory only. Not an authorization to install, approve, or deploy. HOLD and BLOCK stay. Configurations are synthetic lab fixtures.</p>' +
      filtersBar(run) +
      '<div class="kpis">' +
      kpi("▣", historyN, "Runs", "in last 90 days") +
      kpi("◈", counts.applicable, "Applicable patches", "unique KB in this run") +
      kpi("↓", counts.recommended, "Recommended to install", "unique KB", "red") +
      kpi("Ⅱ", counts.held, "Held / Do not install", "unique KB", "purple") +
      "</div><div class=\"grid3\">" +
      panel("Patches by Configuration", glance(run)) +
      panel("Severity (applicable)", severityDonut(run)) +
      "</div>" +
      panel("This run", pipeline(run)) +
      panel("Latest Patches (this run)", patchTable(run, rows)) +
      '<div class="grid2">' +
      panel("Patch Trend (last 90 days)", trendChart()) +
      panel("KB × configurations", '<p class="chart-legend">Vendor risk / product risk. NA = not applicable for this configuration.</p>' + (psirtMatrix(run) || '<p class="empty">No matrix on this run.</p>')) +
      "</div>";
  }

  function findPackage(run, kb) {
    var map = uniqueKbMap(packages(run));
    return map[kb] || uniquePackages(run)[0] || null;
  }

  function engineerOverview(run, pkg) {
    if (!pkg) return '<p class="empty">No patch selected.</p>';
    var letters = lettersForKb(run, pkg.kb);
    var cluster = letters.cluster || {};
    return '<div class="breadcrumb">Patches / ' + esc(pkg.kb) + "</div>" +
      '<div class="pageHead"><div><div class="titleLine"><h1>' + esc(pkg.kb) + "</h1>" +
      badgeSev(pkg.severity) + recStatus(pkg) + "</div><p>" + esc(pkg.title) +
      " · " + esc((pkg.cve_ids || [])[0] || "—") + "</p></div>" +
      '<div class="recommend"><div><small>Recommendation</small><b>' +
      (pkg.include_in_deploy ? "Install" : "Hold / Do not install") +
      "</b><span>Advisory only</span></div></div></div>" +
      engineerTabs() +
      '<div class="engineGrid">' +
      panel("Patch Details", infoRows([
        ["KB number", esc(pkg.kb)],
        ["Title", esc(pkg.title)],
        ["CVE", esc((pkg.cve_ids || []).join(", ") || "—")],
        ["Severity", esc(pkg.severity || "—")],
        ["Official", pkg.official_url ? link(pkg.official_url, "MSRC") : "—"],
        ["Vendor", "Microsoft (MSRC)"]
      ])) +
      panel("Affected Configurations · " + (pkg.stations || []).length,
        '<div class="configList">' + (pkg.stations || []).map(function (id) {
          return "<div><b>" + esc(configLabel(id)) + "</b><span>" + esc(id) + "</span></div>";
        }).join("") + "</div>") +
      panel("Vendor vs Product Risk",
        '<table><thead><tr><th></th><th>Severity</th><th>Likelihood</th><th>Risk</th></tr></thead><tbody>' +
        "<tr><th>Vendor</th><td>" + risk(letters.vendor_severity) + "</td><td>" + risk(letters.vendor_likelihood) +
        "</td><td>" + risk(letters.vendor_risk) + "</td></tr>" +
        "<tr><th>Product</th><td>" + risk(letters.product_severity) + "</td><td>" + risk(letters.product_likelihood) +
        "</td><td>" + risk(letters.product_risk) + "</td></tr></tbody></table>") +
      panel("Technical Impact", cluster.title
        ? "<p>" + esc(cluster.title) + "</p><p class=\"chart-cap\">" + esc(cluster.cluster_key || "") +
          " · " + esc(configLabel(cluster.device_id)) + "</p>" + scoreList(cluster)
        : '<p class="empty">No impact cluster for this KB in this snapshot.</p>') +
      panel("Install vs Skip", '<div class="installSkip"><div class="install"><h3>If we install</h3><ul><li>' +
        esc(scoreLabel(cluster.install_risk)) + "</li></ul></div><div class=\"skip\"><h3>If we skip</h3><ul><li>" +
        esc(scoreLabel(cluster.skip_risk)) + "</li></ul></div></div>") +
      "</div>";
  }

  function engineerTabs() {
    return '<div class="tabs">' +
      ["Overview", "Impact Analysis", "Affected Configurations", "Test Coverage", "Dependencies", "History"].map(function (name) {
        return '<button class="' + (engineerTab === name ? "active" : "") + '" data-eng-tab="' +
          name + '">' + name + "</button>";
      }).join("") + "</div>";
  }

  function impactPage(run, pkg) {
    var letters = lettersForKb(run, pkg.kb);
    var cluster = letters.cluster || {};
    return '<div class="pageHead"><div><h1>Impact Analysis</h1><p>' + esc(pkg.kb) + " · " +
      esc(pkg.title) + "</p></div></div>" + engineerTabs() +
      panel("Vendor vs Product Risk",
        "<table><tr><th></th><th>Severity</th><th>Likelihood</th><th>Risk</th></tr>" +
        "<tr><th>Vendor</th><td>" + risk(letters.vendor_severity) + "</td><td>" + risk(letters.vendor_likelihood) +
        "</td><td>" + risk(letters.vendor_risk) + "</td></tr>" +
        "<tr><th>Product</th><td>" + risk(letters.product_severity) + "</td><td>" + risk(letters.product_likelihood) +
        "</td><td>" + risk(letters.product_risk) + "</td></tr></table>") +
      panel("Decision Logic", infoRows([
        ["If we install", esc(scoreLabel(cluster.install_risk))],
        ["If we skip", esc(scoreLabel(cluster.skip_risk))],
        ["Compatibility", esc(scoreLabel(cluster.compatibility))],
        ["Recommendation", pkg.include_in_deploy ? "Install" : "Hold / Do not install"]
      ])) +
      (cluster.title ? panel("Cluster", scoreList(cluster)) : "");
  }

  function affectedPage(run, pkg) {
    return '<div class="pageHead"><div><h1>Affected Configurations</h1><p>' + esc(pkg.kb) +
      " is applicable to " + (pkg.stations || []).length + " configurations</p></div></div>" +
      engineerTabs() +
      panel("Configuration Scope", (pkg.stations || []).map(function (id) {
        return '<div class="configDetail"><div class="configDetailHead"><div><b>' +
          esc(configLabel(id)) + '</b><span style="display:block;color:#71849c;font-size:10px;margin-top:3px">' +
          esc(id) + "</span></div></div></div>";
      }).join("") || '<p class="empty">No configurations on this KB.</p>');
  }

  function testPage(run, pkg) {
    var tests = (run && run.tests) || {};
    return '<div class="pageHead"><div><h1>Test Coverage</h1><p>' + esc(pkg.kb) +
      " · Host Application Smoke / Regression</p></div></div>" + engineerTabs() +
      panel("This run", tests.outcome
        ? infoRows([
          ["Filter", esc(tests.filter || "Smoke|Regression")],
          ["Outcome", esc(tests.outcome)],
          ["Passed", esc(String(tests.passed))],
          ["Total", esc(String(tests.total))]
        ])
        : '<p class="empty">not in this snapshot</p>');
  }

  function dependenciesPage(run) {
    return '<div class="pageHead"><div><h1>Dependencies</h1><p>Run metadata for Host Application</p></div></div>' +
      engineerTabs() +
      panel("Links", infoRows([
        ["Host Application SHA", run.sha_url ? link(run.sha_url, run.sha) : esc(run.sha || "—")],
        ["FindUpdates run", run.findupdates_url ? link(run.findupdates_url, run.findupdates_run_id) : esc(run.findupdates_run_id || "—")],
        ["Orchestrator run", run.run_url ? link(run.run_url, run.run_id) : esc(run.run_id || "—")]
      ])) +
      panel("Host vs product", '<p class="empty">Component inventory is not in this snapshot.</p>');
  }

  function historyPage(run, pkg) {
    var bundle = (run && run.bundle) || {};
    return '<div class="pageHead"><div><h1>Patch History</h1><p>Run metadata for ' +
      esc(pkg.kb) + "</p></div></div>" + engineerTabs() +
      panel("Run Metadata", infoRows([
        ["Created", esc(run.created_at)],
        ["Orchestrator run", run.run_url ? link(run.run_url, run.run_id) : esc(run.run_id)],
        ["FindUpdates run", run.findupdates_url ? link(run.findupdates_url, run.findupdates_run_id) : esc(run.findupdates_run_id || "—")],
        ["Host Application SHA", run.sha_url ? link(run.sha_url, run.sha) : esc(run.sha || "—")],
        ["Bundle", esc(bundle.bundle_id || "not in this snapshot")]
      ]));
  }

  function engineerPage(run) {
    var pkg = findPackage(run, selectedKb);
    if (engineerTab === "Impact Analysis") return impactPage(run, pkg);
    if (engineerTab === "Affected Configurations") return affectedPage(run, pkg);
    if (engineerTab === "Test Coverage") return testPage(run, pkg);
    if (engineerTab === "Dependencies") return dependenciesPage(run);
    if (engineerTab === "History") return historyPage(run, pkg);
    return engineerOverview(run, pkg);
  }

  function patchList(run) {
    return '<div class="pageHead"><div><h1>Patches</h1><p>All patch findings for this run</p></div></div>' +
      filtersBar(run) + panel(filteredPackages(run).length + " patches matching current filters",
        patchTable(run, filteredPackages(run)));
  }

  function releases(run) {
    var bundle = (run && run.bundle) || {};
    var tests = (run && run.tests) || {};
    var release = (run && run.release) || {};
    var counts = uniqueCounts(run);
    return '<div class="pageHead"><div><h1>Releases</h1><p>Bundle and test facts from this snapshot</p></div></div>' +
      panel("Windows patch bundle", bundle.bundle_id
        ? infoRows([
          ["Bundle", esc(bundle.bundle_id)],
          ["Generated", esc(bundle.generated || "—")],
          ["Recommended", String(counts.recommended)],
          ["Held", String(counts.held)],
          ["Artifacts", "KB manifest + APPLY.ps1"]
        ])
        : '<p class="empty">No Windows patch bundle on this run.</p>') +
      panel("Host Application package", release.zip_name
        ? infoRows([["Zip", esc(release.zip_name)]])
        : '<p class="empty">No application zip on this run.</p>') +
      panel("Tests", tests.outcome
        ? infoRows([["Outcome", esc(tests.outcome)], ["Passed", esc(String(tests.passed))], ["Total", esc(String(tests.total))]])
        : '<p class="empty">not in this snapshot</p>');
  }

  function configurations(run) {
    var names = Object.keys(pageConfigMap).sort();
    if (!names.length) return '<div class="pageHead"><div><h1>Configurations</h1></div></div><p class="empty">No configurations on this run.</p>';
    var html = '<div class="pageHead"><div><h1>Configurations</h1><p>Approved lab configurations and patch applicability</p></div></div>';
    names.forEach(function (id) {
      var label = pageConfigMap[id];
      var rows = uniquePackages(run).filter(function (pkg) {
        return labeledStations(pkg.stations).indexOf(label) !== -1;
      });
      html += panel(label, "<p class=\"chart-cap\">" + esc(id) + " · " + rows.length +
        " relevant patches</p>" + rows.map(function (pkg) {
          return '<div class="metricLine"><button class="link" data-open-kb="' + esc(pkg.kb) + '">' +
            esc(pkg.kb) + "</button>" + badgeSev(pkg.severity) + recStatus(pkg) + "</div>";
        }).join(""));
    });
    return html;
  }

  function reports(run) {
    var findings = (run && run.findings) || [];
    return '<div class="pageHead"><div><h1>Reports</h1><p>Product PDLC findings from this snapshot</p></div></div>' +
      (findings.length
        ? panel("PDLC findings", findings.map(function (item) {
          return '<div class="metricLine"><b>' + esc(item.id) + "</b><span>" + esc(item.title) +
            "</span><span>" + esc(item.countermeasure) + "</span></div>";
        }).join(""))
        : '<p class="empty">No PDLC findings on this run.</p>');
  }

  function settingsPage() {
    return '<div class="pageHead"><div><h1>Settings</h1><p>Advisory GitHub Page</p></div></div>' +
      panel("Scope", infoRows([
        ["Role", "This page cannot start Orchestrator"],
        ["Data", "90-day snapshots from build-pages-site.py"],
        ["Authorization", "HOLD and BLOCK stay"]
      ]));
  }

  function navItems() {
    if (role === "manager") {
      return ["Dashboard", "Patches", "Releases", "Devices & Configurations", "Reports", "Settings"];
    }
    return ["Dashboard", "Patches", "Releases", "Impact Analysis", "Test Coverage", "Dependencies", "Reports", "Settings"];
  }

  function header(run) {
    var created = String((run && run.created_at) || "").replace("T", " ").replace("Z", "Z");
    var runId = (run && run.run_id) || "";
    var opts = (index.runs || []).map(function (row) {
      return '<option value="' + esc(row.run_id) + '"' +
        (String(row.run_id) === String(runId) ? " selected" : "") +
        ">" + esc(row.label || row.run_id) + "</option>";
    }).join("");
    return '<header class="topbar"><div class="brand"><div class="alcon">Alcon</div>' +
      '<div class="product">Windows Patch Management</div></div>' +
      '<div class="roleSwitch"><button class="' + (role === "manager" ? "active" : "") +
      '" data-role="manager">Manager View</button><button class="' +
      (role === "engineer" ? "active" : "") + '" data-role="engineer">Engineer View</button></div>' +
      '<div class="runMeta"><div><b>Last run: ' + esc(created) + "</b><small>Orchestrator #" +
      esc(runId) + '</small></div><select id="run-select">' + opts + "</select></div></header>";
  }

  function sidebar() {
    var current = page;
    if (role === "engineer" && page === "Patches" && selectedKb) current = "Patches";
    return '<aside class="sidebar">' + navItems().map(function (name) {
      var selected = current === name || (name === "Dashboard" && page === "Dashboard" && role === "manager");
      if (role === "engineer" && page === "Dashboard") selected = name === "Dashboard";
      return '<button class="nav' + (page === name ? " selected" : "") + '" data-page="' +
        name + '">' + name + "</button>";
    }).join("") + "</aside>";
  }

  function content(run) {
    if (page === "Dashboard") return role === "manager" ? managerDashboard(run) : engineerPage(run);
    if (page === "Patches") return role === "engineer" && selectedKb ? engineerPage(run) : patchList(run);
    if (page === "Releases") return releases(run);
    if (page === "Devices & Configurations") return configurations(run);
    if (page === "Impact Analysis") return engineerPage(run);
    if (page === "Test Coverage") return engineerPage(run);
    if (page === "Dependencies") return engineerPage(run);
    if (page === "Reports") return reports(run);
    if (page === "Settings") return settingsPage();
    return managerDashboard(run);
  }

  function bind(run) {
    var roleBtns = shell.querySelectorAll("[data-role]");
    roleBtns.forEach(function (btn) {
      btn.addEventListener("click", function () {
        role = btn.getAttribute("data-role");
        page = "Dashboard";
        engineerTab = "Overview";
        paint(run);
      });
    });
    shell.querySelectorAll("[data-page]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        page = btn.getAttribute("data-page");
        if (page === "Impact Analysis" || page === "Test Coverage" || page === "Dependencies") {
          role = "engineer";
          engineerTab = page === "Impact Analysis" ? "Impact Analysis"
            : page === "Test Coverage" ? "Test Coverage" : "Dependencies";
          if (!selectedKb) {
            var first = uniquePackages(run)[0];
            selectedKb = first ? first.kb : "";
          }
        }
        paint(run);
      });
    });
    shell.querySelectorAll("[data-open-kb]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        selectedKb = btn.getAttribute("data-open-kb");
        role = "engineer";
        page = "Patches";
        engineerTab = "Overview";
        paint(run);
      });
    });
    shell.querySelectorAll("[data-eng-tab]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        engineerTab = btn.getAttribute("data-eng-tab");
        role = "engineer";
        page = "Patches";
        paint(run);
      });
    });
    var search = document.getElementById("kb-search");
    if (search) {
      search.value = query;
      search.addEventListener("input", function () {
        query = search.value;
        paint(run);
        var again = document.getElementById("kb-search");
        if (again) {
          again.focus();
          var len = again.value.length;
          again.setSelectionRange(len, len);
        }
      });
    }
    var cfg = document.getElementById("config-filter");
    if (cfg) {
      cfg.addEventListener("change", function () {
        config = cfg.value;
        paint(run);
      });
    }
    var sev = document.getElementById("severity-filter");
    if (sev) {
      sev.addEventListener("change", function () {
        severity = sev.value;
        paint(run);
      });
    }
    var select = document.getElementById("run-select");
    if (select) {
      select.addEventListener("change", function () { show(select.value); });
    }
  }

  function paint(run) {
    currentRun = run;
    if (!run) {
      shell.innerHTML = '<p class="empty">No snapshot for this run.</p>';
      updateFooter(null);
      return;
    }
    pageConfigMap = configNameMap(packages(run));
    shell.innerHTML = header(run) + '<div class="body">' + sidebar() + '<main class="main">' +
      content(run) + "</main></div>";
    bind(run);
    updateFooter(run);
  }

  function show(runId) {
    var snap = snapshots[runId] || snapshots[String(runId)];
    if (snap) {
      paint(snap);
      return;
    }
    fetch("data/history/" + encodeURIComponent(runId) + ".json")
      .then(function (res) { return res.ok ? res.json() : null; })
      .then(paint)
      .catch(function () { paint(null); });
  }

  show(index.latest || (index.runs[0] && index.runs[0].run_id));
})();
