(function () {
  var shell = document.getElementById("shell");
  var index = window.SITE_INDEX || { runs: [], latest: "" };
  var snapshots = window.SITE_SNAPSHOTS || {};
  var currentRun = null;
  var role = "manager";
  var page = "Dashboard";
  var engineerTab = "Overview";
  var selectedKb = "";
  var selectedConfig = "";
  var qaQuestion = "";
  var query = "";
  var severity = "All severities";
  var config = "All configurations";
  var pageConfigMap = {};
  var SEV = { critical: 0, high: 1, important: 1, medium: 2, moderate: 2, low: 3 };

  var SCORE_VALUE_LABELS = {
    required: "Required",
    not_required: "Not required",
    breaks_app: "App may stop working",
    may_break_app: "App may break",
    compatible: "Compatible with the app",
    app_will_fail: "App will fail",
    stays_vulnerable: "Configuration stays exposed",
    no_app_impact: "No effect on the app",
    incompatible: "Not compatible"
  };
  var RISK_HINTS = {
    stays_vulnerable: "If we do not install this KB, the configuration stays exposed on that host path.",
    may_break_app: "If we install this KB, the app on main may break.",
    no_app_impact: "If we skip this KB, the app on main does not change.",
    compatible: "If we install this KB, the app on main should still run."
  };
  var SCORE_FIELD_HINTS = {
    required_for_app: "Does the product on main need this KB to keep working?",
    install_risk: "What happens to the app if we put the KB on the configuration?",
    skip_risk: "What happens if we leave the KB off the configuration?",
    compatibility: "Does current main work with these vendor bits?",
    vendor_severity: "Microsoft / FindUpdates severity as C H M L.",
    vendor_likelihood: "KEV is C. High exploitability is H. Unknown is M.",
    vendor_risk: "Combined vendor severity and likelihood.",
    product_severity: "How severe this is for the published exe on this configuration.",
    product_likelihood: "How reachable the issue is on this configuration. Often L when the component is not loaded.",
    product_risk: "Product risk may be L even when vendor risk is C."
  };

  function formatAiUsage(usage) {
    if (!usage || !usage.provider) return "AI usage was not recorded for this run.";
    if (usage.provider === "offline") return "Analysis used offline scripts.";
    var modelBit = usage.model ? ", model " + usage.model : "";
    return "Analysis used " + usage.provider + modelBit + ".";
  }

  function updateFooter(run) {
    var el = document.getElementById("site-footer");
    if (!el) return;
    el.innerHTML = "Generated by <code>scripts/build-pages-site.py</code>. " +
      esc(formatAiUsage(run && run.ai));
  }

  function text(value, fallback) {
    if (value === null || value === undefined || value === "") return fallback || "—";
    return String(value);
  }

  function esc(value) {
    return text(value).replace(/[&<>"]/g, function (ch) {
      return ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[ch];
    });
  }

  function link(href, label) {
    if (!href) return esc(label);
    return '<a href="' + esc(href) + '">' + esc(label) + "</a>";
  }

  function infoTip(text) {
    return '<span class="info-tip" tabindex="0"><span class="info-mark">i</span><span class="tip">' +
      esc(text) + "</span></span>";
  }

  function scoreLabel(value) {
    var raw = String(value || "").trim();
    if (!raw) return "—";
    return SCORE_VALUE_LABELS[raw] || raw.replace(/_/g, " ");
  }

  function scoreRows(cluster) {
    function hint(field, value) {
      var key = String(value || "").trim();
      if (RISK_HINTS[key]) return RISK_HINTS[key];
      return SCORE_FIELD_HINTS[field];
    }
    var rows = [
      ["Required for app", scoreLabel(cluster && cluster.required_for_app), hint("required_for_app", cluster && cluster.required_for_app)],
      ["If we install", scoreLabel(cluster && cluster.install_risk), hint("install_risk", cluster && cluster.install_risk)],
      ["If we skip", scoreLabel(cluster && cluster.skip_risk), hint("skip_risk", cluster && cluster.skip_risk)],
      ["Compatibility", scoreLabel(cluster && cluster.compatibility), hint("compatibility", cluster && cluster.compatibility)]
    ];
    [
      ["Vendor severity", "vendor_severity"],
      ["Vendor likelihood", "vendor_likelihood"],
      ["Vendor risk", "vendor_risk"],
      ["Product severity", "product_severity"],
      ["Product likelihood", "product_likelihood"],
      ["Product risk", "product_risk"]
    ].forEach(function (item) {
      rows.push([item[0], (cluster && cluster[item[1]]) || "NA", SCORE_FIELD_HINTS[item[1]]]);
    });
    return rows;
  }

  function scoreList(cluster) {
    var html = '<dl class="score-list">';
    scoreRows(cluster).forEach(function (row) {
      html += "<div><span class=\"info-slot\">" + infoTip(row[2]) +
        "</span><dt>" + esc(row[0]) + "</dt><dd>" + esc(row[1]) + "</dd></div>";
    });
    return html + "</dl>";
  }

  function realClusters(run) {
    return (run && run.clusters || []).filter(function (item) {
      return item && item.cluster_key !== "ai-usage" && item.title !== "ai-usage";
    });
  }

  function configNameMap(packages) {
    var seen = {};
    (packages || []).forEach(function (item) {
      (item.stations || []).forEach(function (raw) {
        var name = String(raw || "").trim();
        if (name) seen[name] = 1;
      });
    });
    var map = {};
    Object.keys(seen).sort().forEach(function (name, i) {
      map[name] = "Config" + (i + 1);
    });
    return map;
  }

  function configLabel(name) {
    var key = String(name || "").trim();
    return shortConfig(pageConfigMap[key] || key);
  }

  function shortConfig(value) {
    return String(value || "").trim().replace(/^Configurations/, "Config");
  }

  function sameConfig(left, right) {
    var a = shortConfig(left);
    var b = shortConfig(right);
    return Boolean(a) && a === b;
  }

  function labeledStations(ids) {
    return (ids || []).map(function (id) { return configLabel(id); }).join(", ");
  }

  function configNames() {
    return Object.keys(pageConfigMap).sort().map(function (id) { return pageConfigMap[id]; });
  }

  function packages(run) {
    return ((run && run.bundle) || {}).packages || [];
  }

  function uniqueKbMap(list) {
    var map = {};
    (list || []).forEach(function (item, index) {
      var kb = String(item.kb || "").trim() || ("row-" + index);
      if (!map[kb]) {
        map[kb] = item;
        return;
      }
      if (item.include_in_deploy && !map[kb].include_in_deploy) map[kb] = item;
    });
    return map;
  }

  function uniquePackages(run) {
    var map = uniqueKbMap(packages(run));
    return Object.keys(map).map(function (kb) { return map[kb]; });
  }

  function uniqueCounts(run) {
    var rec = 0;
    var hold = 0;
    uniquePackages(run).forEach(function (item) {
      if (item.include_in_deploy) rec += 1;
      else hold += 1;
    });
    return { applicable: rec + hold, recommended: rec, held: hold };
  }

  function stationCount(bundle) {
    var counts = (bundle && bundle.counts) || {};
    if (counts.stations) return Number(counts.stations) || 0;
    var seen = {};
    ((bundle && bundle.packages) || []).forEach(function (item) {
      (item.stations || []).forEach(function (name) {
        if (name) seen[name] = 1;
      });
    });
    return Object.keys(seen).length;
  }

  function displayProduct(run) {
    var raw = String((run && run.product) || "").trim();
    if (!raw || raw === "HostApplication" || raw === "DesktopApplication") return "Host Application";
    return raw;
  }

  function stationProfiles(run) {
    return ((run && run.bundle) || {}).stations || [];
  }

  function stationProfile(run, id) {
    var needle = String(id || "").trim();
    var list = stationProfiles(run);
    for (var i = 0; i < list.length; i++) {
      if (String(list[i].device_id || "") === needle) return list[i];
    }
    return {};
  }

  function uniqueStrings(values) {
    var found = [];
    (values || []).forEach(function (item) {
      var text = String(item || "").trim();
      if (text && found.indexOf(text) === -1) found.push(text);
    });
    return found;
  }

  function configUpdateCounts(list) {
    var recommended = {};
    var ignored = {};
    (list || []).forEach(function (item, index) {
      var kb = String(item.kb || ("row-" + index));
      var names = item.stations || [];
      var bucket = item.include_in_deploy ? recommended : ignored;
      names.forEach(function (raw) {
        var name = String(raw || "").trim();
        if (!name) return;
        if (!bucket[name]) bucket[name] = {};
        bucket[name][kb] = 1;
      });
    });
    var names = Object.keys(recommended).concat(Object.keys(ignored)).filter(function (name, i, all) {
      return all.indexOf(name) === i;
    }).sort();
    return names.map(function (name) {
      return {
        name: name,
        recommended: Object.keys(recommended[name] || {}).length,
        ignored: Object.keys(ignored[name] || {}).length
      };
    });
  }

  function configChartCaption(rows, runId, historyN) {
    var recommended = 0;
    var ignored = 0;
    (rows || []).forEach(function (row) {
      recommended += Number(row.recommended || 0);
      ignored += Number(row.ignored || 0);
    });
    var runBit = runId ? "This run (" + runId + ")" : "This run";
    var line = runBit + ": " + ignored + " applicable for our platform · " +
      recommended + " recommended to install across " + (rows || []).length +
      " configurations.";
    if (!historyN || historyN < 2) return line + " History will grow with later runs.";
    return line + " " + historyN + " runs in the last 90 days.";
  }

  function configBars(rows) {
    var list = rows || [];
    if (!list.length) {
      return '<p class="empty">No configuration counts on this run.</p>';
    }
    var n = list.length;
    var w = Math.max(640, n * 90);
    var h = 220;
    var padL = 36;
    var padR = 16;
    var padT = 24;
    var padB = 56;
    var innerW = w - padL - padR;
    var innerH = h - padT - padB;
    var groupW = innerW / n;
    var max = 1;
    list.forEach(function (row) {
      if (row.recommended > max) max = row.recommended;
      if (row.ignored > max) max = row.ignored;
    });
    var barW = Math.min(18, groupW / 2 - 6);
    var svg = '<svg viewBox="0 0 ' + w + " " + h + '" class="chart">';
    svg += '<text x="0" y="' + (padT + 4) + '" class="chart-lab">' + max + "</text>";
    svg += '<text x="0" y="' + (padT + innerH + 4) + '" class="chart-lab">0</text>';
    list.forEach(function (row, i) {
      var cx = padL + i * groupW + groupW / 2;
      var recH = row.recommended / max * innerH;
      var ignH = row.ignored / max * innerH;
      var ignX = cx - barW - 2;
      var recX = cx + 2;
      if (ignH > 0) {
        svg += '<rect x="' + ignX + '" y="' + (padT + innerH - ignH) + '" width="' + barW +
          '" height="' + ignH + '" fill="#0b57b8"/>';
      }
      if (recH > 0) {
        svg += '<rect x="' + recX + '" y="' + (padT + innerH - recH) + '" width="' + barW +
          '" height="' + recH + '" fill="#ef3e4e"/>';
      }
      svg += '<text x="' + (ignX + barW / 2) + '" y="' + (padT + innerH - ignH - 4) +
        '" text-anchor="middle" class="chart-n">' + row.ignored + "</text>";
      svg += '<text x="' + (recX + barW / 2) + '" y="' + (padT + innerH - recH - 4) +
        '" text-anchor="middle" class="chart-n">' + row.recommended + "</text>";
      svg += '<text x="' + cx + '" y="' + (h - 20) + '" text-anchor="middle" class="chart-lab">' +
        esc(configLabel(row.name)) + "</text>";
    });
    return svg + "</svg>";
  }

  function psirtMatrix(run) {
    var matrix = (run && run.psirt_matrix) || {};
    var columns = matrix.columns || [];
    var rows = matrix.rows || [];
    if (!columns.length || !rows.length) return "";
    var parts = ['<div class="matrix-wrap"><table><thead><tr><th>KB</th>'];
    columns.forEach(function (name) { parts.push("<th>" + esc(name) + "</th>"); });
    parts.push("</tr></thead><tbody>");
    rows.forEach(function (row) {
      parts.push("<tr><td>" + esc(row.kb) + "</td>");
      (row.cells || []).forEach(function (cell) { parts.push("<td>" + esc(cell) + "</td>"); });
      parts.push("</tr>");
    });
    parts.push("</tbody></table></div>");
    return parts.join("");
  }

  function glance(run) {
    var rows = configUpdateCounts(packages(run));
    var historyN = allSnapshots().length;
    var parts = [];
    parts.push('<p class="chart-cap">' + esc(configChartCaption(rows, run.run_id, historyN)) + "</p>");
    parts.push('<p class="chart-legend">Blue applicable for our platform · red recommended to install</p>');
    parts.push(configBars(rows));
    return parts.join("");
  }

  function allSnapshots() {
    var list = [];
    Object.keys(snapshots).forEach(function (id) { list.push(snapshots[id]); });
    list.sort(function (a, b) { return String(a.created_at || "").localeCompare(String(b.created_at || "")); });
    return list;
  }

  var LETTER_RANK = { NA: 0, L: 1, M: 2, H: 3, C: 4 };
  var RISK_MATRIX = {
    CC: "C", CH: "H", CM: "H", CL: "M",
    HC: "C", HH: "H", HM: "M", HL: "M",
    MC: "H", MH: "M", MM: "M", ML: "L",
    LC: "H", LH: "M", LM: "L", LL: "L"
  };

  function letterSeverity(value) {
    var text = String(value || "").trim().toLowerCase();
    if (text === "critical" || text === "c") return "C";
    if (text === "high" || text === "important" || text === "h") return "H";
    if (text === "medium" || text === "moderate" || text === "m") return "M";
    if (text === "low" || text === "very low" || text === "none" || text === "l") return "L";
    return "NA";
  }

  function vendorLikelihood(kev, exp) {
    var known = String(kev || "").trim().toLowerCase();
    if (known === "true" || known === "yes" || known === "1") return "C";
    var text = String(exp || "").trim().toLowerCase();
    if (text === "high") return "H";
    if (text === "medium" || text === "moderate") return "M";
    if (text === "low" || text === "none") return "L";
    return "M";
  }

  function overallRisk(severity, likelihood) {
    if (!severity || !likelihood || severity === "NA" || likelihood === "NA") return "NA";
    return RISK_MATRIX[severity + likelihood] || "M";
  }

  function worstLetter(values) {
    var best = "NA";
    (values || []).forEach(function (item) {
      var letter = String(item || "NA");
      if ((LETTER_RANK[letter] || 0) > (LETTER_RANK[best] || 0)) best = letter;
    });
    return best;
  }

  function vendorFromPkg(pkg) {
    var item = pkg || {};
    if (item.vendor_risk && item.vendor_risk !== "NA") {
      return {
        severity: item.vendor_severity || "NA",
        likelihood: item.vendor_likelihood || "NA",
        risk: item.vendor_risk
      };
    }
    var sev = letterSeverity(item.severity);
    var lik = vendorLikelihood(item.known_exploited, item.exploitability);
    return { severity: sev, likelihood: lik, risk: overallRisk(sev, lik) };
  }

  function productFromCluster(cluster) {
    var item = cluster || {};
    if (item.product_risk && item.product_risk !== "NA") {
      return {
        severity: item.product_severity || "NA",
        likelihood: item.product_likelihood || "NA",
        risk: item.product_risk
      };
    }
    var required = String(item["required_for_app"] || "").trim();
    var install = String(item["install_risk"] || "").trim();
    var skip = String(item["skip_risk"] || "").trim();
    var sev = "NA";
    var lik = "NA";
    if (required === "required" || skip === "app_will_fail") { sev = "C"; lik = "H"; }
    else if (skip === "no_app_impact") { sev = "L"; lik = "L"; }
    else if (skip === "stays_vulnerable") { sev = "M"; lik = "M"; }
    else if (install === "may_break_app" || install === "breaks_app") { sev = "M"; lik = "L"; }
    else if (required === "not_required") { sev = "L"; lik = "L"; }
    if (skip === "no_app_impact") return { severity: "L", likelihood: "L", risk: "L" };
    return { severity: sev, likelihood: lik, risk: overallRisk(sev, lik) };
  }

  function extractKbs(text) {
    var found = [];
    String(text || "").replace(/\bKB\d+\b/gi, function (match) {
      var kb = match.toUpperCase();
      if (found.indexOf(kb) === -1) found.push(kb);
      return match;
    });
    return found;
  }

  function clusterHasKb(cluster, kb) {
    var needle = String(kb || "").trim().toUpperCase();
    var pkgs = cluster.packages || [];
    if (pkgs.some(function (item) { return String(item).toUpperCase() === needle; })) return true;
    if (extractKbs(cluster.title).indexOf(needle) !== -1) return true;
    if (extractKbs(cluster.impact).indexOf(needle) !== -1) return true;
    if (extractKbs(cluster.advisory_id).indexOf(needle) !== -1) return true;
    if (extractKbs(cluster.body).indexOf(needle) !== -1) return true;
    return false;
  }

  function clusterMatchesPkg(cluster, pkg) {
    var item = pkg || {};
    if (clusterHasKb(cluster, item.kb)) return true;
    var device = String(cluster.device_id || "").trim();
    var named = String(cluster.config_label || "").trim();
    return (item.stations || []).some(function (raw) {
      var id = String(raw || "").trim();
      var label = configLabel(id);
      return sameConfig(device, id) || sameConfig(device, label) || sameConfig(named, label) || sameConfig(named, id);
    });
  }

  function clustersForKb(run, kb) {
    var pkg = uniqueKbMap(packages(run))[kb] || { kb: kb, stations: [] };
    var all = realClusters(run);
    var direct = all.filter(function (item) { return clusterMatchesPkg(item, pkg); });
    var keys = {};
    direct.forEach(function (item) {
      var key = String(item.cluster_key || "").trim();
      if (key) keys[key] = 1;
    });
    if (!Object.keys(keys).length) return direct;
    return all.filter(function (item) {
      return clusterMatchesPkg(item, pkg) || keys[String(item.cluster_key || "").trim()];
    });
  }

  function clusterImpactText(cluster) {
    var raw = String((cluster && cluster.impact) || "").trim();
    if (raw) return raw;
    var body = String((cluster && cluster.body) || "").trim();
    if (body) return body.length > 1200 ? body.slice(0, 1200) + "…" : body;
    var title = String((cluster && cluster.title) || "");
    var idx = title.lastIndexOf(" - ");
    if (idx !== -1) return title.slice(idx + 3).trim();
    return "";
  }

  function lettersForKb(run, kb) {
    var pkg = uniqueKbMap(packages(run))[kb] || {};
    var vendor = vendorFromPkg(pkg);
    var list = clustersForKb(run, kb);
    var products = list.map(productFromCluster);
    var product = {
      severity: worstLetter(products.map(function (item) { return item.severity; })),
      likelihood: worstLetter(products.map(function (item) { return item.likelihood; })),
      risk: worstLetter(products.map(function (item) { return item.risk; }))
    };
    return {
      vendor: vendor.risk,
      product: product.risk,
      vendor_severity: vendor.severity,
      vendor_likelihood: vendor.likelihood,
      vendor_risk: vendor.risk,
      product_severity: product.severity,
      product_likelihood: product.likelihood,
      product_risk: product.risk,
      cluster: list[0] || {},
      clusters: list
    };
  }

  function impactHtml(text) {
    var raw = String(text || "").trim();
    if (!raw) return "";
    return esc(raw).replace(/\n/g, "<br>");
  }

  function clusterKeyLabel(key) {
    var raw = String(key || "").trim();
    var names = {
      "shell-launch": "Shell / WinExe",
      "dwm-wpf": "DWM / Graphics",
      "schannel-tls": "Schannel / TLS",
      "win32k-wpf": "Win32k / WPF",
      "ntfs-notes": "NTFS / notes"
    };
    return names[raw] || raw;
  }

  function clusterKeyCounts(run) {
    var counts = {};
    realClusters(run).forEach(function (item) {
      var key = String(item.cluster_key || "other").trim() || "other";
      counts[key] = (counts[key] || 0) + 1;
    });
    return Object.keys(counts).sort(function (a, b) { return counts[b] - counts[a]; }).map(function (key) {
      return { label: key, value: counts[key] };
    });
  }

  function badgeSev(value) {
    var raw = String(value || "").toLowerCase();
    var cls = "low";
    if (raw === "critical") cls = "critical";
    else if (raw === "high" || raw === "important") cls = "high";
    else if (raw === "medium" || raw === "moderate") cls = "medium";
    return '<span class="badge ' + cls + '">' + esc(value || "—") + "</span>";
  }

  function recBadge(pkg) {
    return pkg.include_in_deploy
      ? '<span class="badge install">Install</span>'
      : '<span class="badge hold">Hold</span>';
  }

  function recStatus(pkg) {
    return pkg.include_in_deploy
      ? '<span class="status install">Install</span>'
      : '<span class="status hold">Hold</span>';
  }

  function actionLabel(action) {
    var raw = String(action || "").trim();
    if (!raw) return "—";
    if (raw === "candidate_for_validation") return "Recommended to validate";
    if (raw === "do_not_install") return "Do not install";
    if (raw === "not_in_scope") return "Not in scope";
    return raw.replace(/_/g, " ");
  }

  function risk(letter) {
    var t = String(letter || "NA");
    return '<span class="risk ' + esc(t) + '">' + esc(t) + "</span>";
  }

  function panel(title, body, action) {
    return '<section class="panel"><div class="panelHead"><h2>' + title + "</h2>" +
      (action || "") + "</div>" + body + "</section>";
  }

  function miniGrid(rows) {
    return '<div class="miniGrid">' + (rows || []).map(function (row) {
      return "<div><span>" + esc(row[0]) + "</span><b>" + esc(text(row[1])) + "</b></div>";
    }).join("") + "</div>";
  }

  function infoRows(rows) {
    return '<div class="info">' + rows.map(function (row) {
      return "<div><span>" + row[0] + "</span><b>" + row[1] + "</b></div>";
    }).join("") + "</div>";
  }

  function donutChart(slices, centerLabel) {
    var list = slices || [];
    var total = list.reduce(function (sum, item) { return sum + Number(item.value || 0); }, 0);
    if (!total) return '<p class="empty">No counts on this run.</p>';
    var start = 0;
    var arcs = "";
    list.forEach(function (item) {
      var v = Number(item.value || 0);
      if (!v) return;
      var a = v / total * 360;
      var x1 = 65 + 50 * Math.cos((start - 90) * Math.PI / 180);
      var y1 = 65 + 50 * Math.sin((start - 90) * Math.PI / 180);
      var x2 = 65 + 50 * Math.cos((start + a - 90) * Math.PI / 180);
      var y2 = 65 + 50 * Math.sin((start + a - 90) * Math.PI / 180);
      arcs += '<path d="M 65 65 L ' + x1 + " " + y1 + " A 50 50 0 " + (a > 180 ? 1 : 0) +
        " 1 " + x2 + " " + y2 + ' Z" fill="' + item.color + '"></path>';
      start += a;
    });
    return '<div class="donutWrap"><svg class="donut" viewBox="0 0 130 150">' + arcs +
      '<circle cx="65" cy="65" r="31" fill="white"></circle>' +
      '<text x="65" y="64" text-anchor="middle" font-size="22" font-weight="800" fill="#18365e">' +
      total + '</text><text x="65" y="80" text-anchor="middle" font-size="9" fill="#71849c">' +
      esc(centerLabel || "") + "</text></svg>" +
      '<div class="legend">' + list.map(function (item) {
        return "<div><i style=\"background:" + item.color + '"></i><span>' + esc(item.label) +
          "</span><b>" + item.value + " (" + Math.round(item.value / total * 100) + "%)</b></div>";
      }).join("") + "</div></div>";
  }

  function severityDonut(run) {
    var buckets = { Critical: 0, High: 0, Medium: 0, Low: 0 };
    uniquePackages(run).forEach(function (item) {
      var raw = String(item.severity || "").toLowerCase();
      if (raw === "critical") buckets.Critical += 1;
      else if (raw === "high" || raw === "important") buckets.High += 1;
      else if (raw === "medium" || raw === "moderate") buckets.Medium += 1;
      else buckets.Low += 1;
    });
    return donutChart([
      { label: "Critical", value: buckets.Critical, color: "#0b57b8" },
      { label: "High", value: buckets.High, color: "#3186e5" },
      { label: "Medium", value: buckets.Medium, color: "#8abcf2" },
      { label: "Low", value: buckets.Low, color: "#cbd5e1" }
    ], "Applicable");
  }

  function findingsDonut(run) {
    var buckets = { present: 0, absent: 0, partial: 0 };
    ((run && run.findings) || []).forEach(function (item) {
      var raw = String(item.countermeasure || "").trim().toLowerCase();
      if (raw === "present") buckets.present += 1;
      else if (raw === "absent") buckets.absent += 1;
      else buckets.partial += 1;
    });
    if (!(buckets.present + buckets.absent + buckets.partial)) {
      return '<p class="empty">No PDLC findings on this run.</p>';
    }
    return donutChart([
      { label: "present", value: buckets.present, color: "#22a05a" },
      { label: "absent", value: buckets.absent, color: "#d92828" },
      { label: "partial", value: buckets.partial, color: "#f0b429" }
    ], "Findings");
  }

  function pipeline(run) {
    var pkgN = uniquePackages(run).length;
    var clusterN = realClusters(run).length;
    var tests = (run && run.tests) || {};
    var findings = (run && run.findings) || [];
    var evidenceN = findings.filter(function (item) { return String(item.evidence || "").trim(); }).length;
    var testBit = tests.outcome
      ? String(tests.outcome) + " " + text(tests.passed, "0") + "/" + text(tests.total, "0")
      : "not in this snapshot";
    var bundleId = ((run && run.bundle) || {}).bundle_id || "";
    var rows = [
      ["Packages", pkgN, Math.max(pkgN, 1), String(pkgN)],
      ["Impact clusters", clusterN, Math.max(clusterN, 1), String(clusterN)],
      ["Tests", tests.outcome ? Number(tests.passed || 0) : 0, Math.max(Number(tests.total || 0), 1), testBit],
      ["Findings with evidence", evidenceN, Math.max(findings.length, 1), evidenceN + "/" + findings.length],
      ["Bundle", bundleId ? 1 : 0, 1, bundleId ? "yes" : "—"]
    ];
    return '<div class="pipelineRows">' + rows.map(function (row) {
      var pct = Math.round(row[1] / row[2] * 100);
      return '<div class="pipe"><span>' + row[0] + "</span><div><i style=\"width:" + pct +
        '%"></i></div><b>' + esc(String(row[3])) + "</b></div>";
    }).join("") + "</div>";
  }

  function trendChart() {
    var points = allSnapshots().map(function (item) {
      var counts = uniqueCounts(item);
      return {
        run_id: item.run_id,
        created_at: item.created_at,
        recommended: counts.recommended,
        held: counts.held
      };
    });
    if (!points.length) return '<p class="empty">History will grow with later runs.</p>';
    var w = 700;
    var h = 180;
    var padL = 28;
    var padR = 12;
    var padT = 16;
    var padB = 24;
    var innerW = w - padL - padR;
    var innerH = h - padT - padB;
    var max = 1;
    points.forEach(function (p) {
      if (p.recommended > max) max = p.recommended;
      if (p.held > max) max = p.held;
    });
    function xAt(i) {
      if (points.length === 1) return padL + innerW / 2;
      return padL + i * innerW / (points.length - 1);
    }
    function yAt(v) { return padT + innerH - (Number(v) / max) * innerH; }
    function path(key) {
      return points.map(function (p, i) {
        return (i ? "L" : "M") + xAt(i) + " " + yAt(p[key]);
      }).join(" ");
    }
    var first = String(points[0].created_at || "").slice(0, 10);
    var last = String(points[points.length - 1].created_at || "").slice(0, 10);
    return '<div class="trend"><svg viewBox="0 0 ' + w + " " + h +
      '" preserveAspectRatio="none"><path d="' + path("held") +
      '" fill="none" stroke="#0b57b8" stroke-width="4"/><path d="' + path("recommended") +
      '" fill="none" stroke="#ef3e4e" stroke-width="3"/></svg><div class="axis"><span>' +
      esc(first) + "</span><span>" + esc(last) + "</span></div></div>";
  }

  function filteredPackages(run) {
    return uniquePackages(run).filter(function (pkg) {
      var hay = (pkg.kb + " " + pkg.title).toLowerCase();
      if (query && hay.indexOf(query.toLowerCase()) === -1) return false;
      if (severity !== "All severities") {
        if (String(pkg.severity || "").toUpperCase() !== severity) return false;
      }
      if (config !== "All configurations") {
        var labels = labeledStations(pkg.stations);
        if (labels.indexOf(config) === -1) return false;
      }
      return true;
    });
  }

  function patchTable(run, rows) {
    if (!rows.length) return '<p class="empty">No patches match the selected filters.</p>';
    var html = '<div style="overflow:auto"><table><thead><tr><th>KB</th><th>Title</th><th>Severity</th><th>Recommendation</th><th>Config</th><th>CVEs</th><th>Vendor</th><th>Product</th><th>Status</th><th></th></tr></thead><tbody>';
    rows.forEach(function (pkg) {
      var letters = lettersForKb(run, pkg.kb);
      html += "<tr><td><button class=\"link\" data-open-kb=\"" + esc(pkg.kb) + "\">" + esc(pkg.kb) +
        "</button></td><td>" + esc(pkg.title) + "</td><td>" + badgeSev(pkg.severity) +
        "</td><td>" + recBadge(pkg) + "</td><td>" + esc(labeledStations(pkg.stations)) +
        "</td><td>" + esc((pkg.cve_ids || []).join(", ") || "—") +
        "</td><td>" + risk(letters.vendor) + "</td><td>" + risk(letters.product) +
        "</td><td>" + recStatus(pkg) + "</td><td><button class=\"view\" data-open-kb=\"" +
        esc(pkg.kb) + "\">View</button></td></tr>";
    });
    return html + "</tbody></table></div>";
  }

  function filtersBar(run) {
    var names = configNames();
    var sevOpts = ["All severities", "CRITICAL", "HIGH", "MEDIUM", "LOW"];
    return '<div class="filters"><div class="search"><input id="kb-search" placeholder="Search KB or title" value="' +
      esc(query) + '"></div><select id="config-filter"><option>All configurations</option>' +
      names.map(function (name) {
        return "<option" + (config === name ? " selected" : "") + ">" + esc(name) + "</option>";
      }).join("") +
      '</select><select id="severity-filter">' +
      sevOpts.map(function (name) {
        return "<option" + (severity === name ? " selected" : "") + ">" + esc(name) + "</option>";
      }).join("") +
      "</select></div>";
  }

  function kpi(icon, value, label, note, cls) {
    return '<div class="kpi ' + (cls || "") + '"><div class="kpiIcon">' + icon +
      "</div><div><strong>" + esc(String(value)) + "</strong><b>" + esc(label) +
      "</b><span>" + esc(note) + "</span></div></div>";
  }

  function componentBars(run) {
    var rows = clusterKeyCounts(run).slice(0, 6);
    if (!rows.length) return '<p class="empty">No impact cluster keys on this run.</p>';
    var max = rows[0].value || 1;
    return '<div class="components">' + rows.map(function (row) {
      var width = Math.round(row.value / max * 100);
      return "<div><span>" + esc(clusterKeyLabel(row.label)) + "</span><div><i style=\"width:" + width +
        '%"></i></div><b>' + row.value + "</b></div>";
    }).join("") + "</div>";
  }

  function managerDashboard(run) {
    var counts = uniqueCounts(run);
    var historyN = allSnapshots().length;
    var rows = filteredPackages(run);
    return '<div class="pageHead"><div><h1>Patch Management Overview</h1>' +
      "<p>Executive summary of Microsoft Windows updates for Host Application configurations</p></div>" +
      '<div class="period">Last 90 days</div></div>' +
      '<p class="banner">Advisory only. Not an authorization to install, approve, or deploy. HOLD and BLOCK stay. Configurations are synthetic lab fixtures.</p>' +
      filtersBar(run) +
      '<div class="kpis">' +
      kpi("▣", historyN, "Runs", "in last 90 days") +
      kpi("◈", counts.applicable, "Applicable patches", "unique KB in this run") +
      kpi("↓", counts.recommended, "Recommended to install", "unique KB", "red") +
      kpi("Ⅱ", counts.held, "Held / Do not install", "unique KB", "purple") +
      kpi("◎", ((run && run.findings) || []).length, "PDLC findings", "this run", "green") +
      "</div><div class=\"grid3\">" +
      panel("Patches by Configuration", glance(run)) +
      panel("Product findings", findingsDonut(run)) +
      panel("Severity (applicable)", severityDonut(run)) +
      "</div>" +
      panel("This run", pipeline(run)) +
      panel("Latest Patches (this run)", patchTable(run, rows),
        '<button class="view" data-view-all>View all</button>') +
      '<div class="grid2">' +
      panel("Patch Trend (last 90 days)", trendChart()) +
      panel("Top impact cluster keys", componentBars(run)) +
      "</div>" +
      panel("KB × configurations", '<p class="chart-legend">Vendor risk / product risk. NA = not applicable for this configuration.</p>' + (psirtMatrix(run) || '<p class="empty">No matrix on this run.</p>'));
  }

  function findPackage(run, kb) {
    var map = uniqueKbMap(packages(run));
    return map[kb] || uniquePackages(run)[0] || null;
  }

  function impactBlocks(run, pkg) {
    var letters = lettersForKb(run, pkg.kb);
    var list = letters.clusters || [];
    if (!list.length) {
      return '<p class="empty">No impact cluster for this KB in this snapshot.</p>';
    }
    return list.map(function (cluster) {
      var body = impactHtml(clusterImpactText(cluster));
      return "<div class=\"tech\"><b>" + esc(cluster.title || cluster.cluster_key) + "</b>" +
        "<p class=\"chart-cap\">" + esc(cluster.cluster_key || "") + " · " +
        esc(cluster.config_label || configLabel(cluster.device_id)) +
        (cluster.packages && cluster.packages.length ? " · " + esc(cluster.packages.join(", ")) : "") +
        "</p>" +
        (body ? "<p>" + body + "</p>" : "") + scoreList(cluster) + "</div>";
    }).join("");
  }

  function clusterForStation(list, id) {
    var label = configLabel(id);
    var rows = list || [];
    for (var i = 0; i < rows.length; i++) {
      var item = rows[i];
      if (sameConfig(item.device_id, id) || sameConfig(item.device_id, label) || sameConfig(item.config_label, label) || sameConfig(item.config_label, id)) {
        return item;
      }
    }
    return null;
  }

  function citedFileList(run, clusters) {
    var found = [];
    function add(path) {
      var text = String(path || "").trim();
      if (text && found.indexOf(text) === -1) found.push(text);
    }
    (clusters || []).forEach(function (cluster) {
      String((cluster && cluster.body) || (cluster && cluster.impact) || "").replace(/`([^`]+)`/g, function (_, path) {
        add(path);
        return _;
      });
      ((cluster && cluster.impact_files) || []).forEach(add);
    });
    ((run && run.findings) || []).forEach(function (item) {
      (item.impact_files || []).forEach(add);
    });
    if (!found.length) return "";
    return '<div class="tech">' + found.map(function (path) {
      return "<code>" + esc(path) + "</code>";
    }).join("") + "</div>";
  }

  function testSnippet(run) {
    var tests = (run && run.tests) || {};
    var planned = [];
    ((run && run.findings) || []).forEach(function (item) {
      (item.tests_to_run || []).forEach(function (row) {
        if (planned.indexOf(row) === -1) planned.push(row);
      });
    });
    var bits = [];
    if (tests.outcome) {
      bits.push(String(tests.outcome) + " " + text(tests.passed, "0") + "/" + text(tests.total, "0"));
    }
    planned.forEach(function (row) { bits.push(row); });
    if (!bits.length) return '<p class="empty">not in this snapshot</p>';
    return "<p>" + bits.map(function (row) { return esc(row); }).join(" · ") + "</p>";
  }

  function engineerBack() {
    return '<div class="detailActions"><button class="ghost" data-all-patches>← All Patches</button></div>';
  }

  function engineerStepper(run) {
    var tests = (run && run.tests) || {};
    var findings = (run && run.findings) || [];
    var bundle = (run && run.bundle) || {};
    var release = (run && run.release) || {};
    var flags = [
      uniquePackages(run).length > 0,
      realClusters(run).length > 0,
      Boolean(tests.outcome),
      findings.length > 0 || Boolean(release.zip_name) || Boolean(bundle.bundle_id)
    ];
    var labels = ["Packages", "Impact clusters", "Tests", "Findings or zip"];
    var current = -1;
    var i;
    for (i = 0; i < flags.length; i++) {
      if (!flags[i]) { current = i; break; }
    }
    return '<div class="stepper">' + labels.map(function (name, idx) {
      var cls = "step";
      if (flags[idx] && (current === -1 || idx < current)) cls += " done";
      else if (idx === current) cls += " current";
      return '<div class="' + cls + '">' + esc(name) + "</div>";
    }).join("") + "</div>";
  }

  function engineerHead(run, headingHtml) {
    return engineerBack() + headingHtml + engineerStepper(run) + engineerTabs();
  }

  function engineerOverview(run, pkg) {
    if (!pkg) return '<p class="empty">No patch selected.</p>';
    var letters = lettersForKb(run, pkg.kb);
    var list = letters.clusters || [];
    var cluster = list[0] || {};
    var installSkip = cluster.cluster_key
      ? [scoreLabel(cluster.install_risk), scoreLabel(cluster.skip_risk)]
      : ["not in this snapshot", "not in this snapshot"];
    return engineerHead(run,
      '<div class="pageHead"><div><div class="titleLine"><h1>' + esc(pkg.kb) + "</h1>" +
      badgeSev(pkg.severity) + recStatus(pkg) + "</div><p>" + esc(pkg.title) +
      " · " + esc((pkg.cve_ids || [])[0] || "—") +
      (list.length ? " · " + list.length + " impact cluster(s)" : "") + "</p></div>" +
      '<div class="recommend"><div><small>Recommendation</small><b>' +
      (pkg.include_in_deploy ? "Install" : "Hold / Do not install") +
      "</b><span>Advisory only</span></div></div></div>") +
      '<div class="callout"><b>Next action</b><p>Review impact analysis and test coverage for this KB. Advisory only.</p>' +
      '<div class="actionRow"><button class="secondary" data-eng-tab="Impact Analysis">Impact Analysis</button>' +
      '<button class="secondary" data-eng-tab="Test Coverage">Test Coverage</button></div></div>' +
      '<div class="engineGrid">' +
      panel("Patch Details", infoRows([
        ["KB number", esc(pkg.kb)],
        ["Title", esc(pkg.title)],
        ["CVE", esc((pkg.cve_ids || []).join(", ") || "—")],
        ["Severity", esc(pkg.severity || "—")],
        ["Action", esc(actionLabel(pkg.action))],
        ["KEV", esc(pkg.known_exploited || "—")],
        ["Exploitability", esc(pkg.exploitability || "—")],
        ["OS products", esc((pkg.os_products || []).join(", ") || "—")],
        ["Deployment groups", esc((pkg.deployment_groups || []).join(", ") || "—")],
        ["Official", pkg.official_url ? link(pkg.official_url, "MSRC") : "—"],
        ["Vendor", "Microsoft (MSRC)"]
      ])) +
      panel("Affected Configurations · " + (pkg.stations || []).length,
        '<div class="configList">' + (pkg.stations || []).map(function (id) {
          var profile = stationProfile(run, id);
          var bits = [profile.os_product, profile.os_build, profile.device_role].filter(Boolean);
          return "<div><b>" + esc(configLabel(id)) + "</b><span>" + esc(id) +
            (bits.length ? " · " + esc(bits.join(" · ")) : "") +
            '</span><button class="view" data-open-config="' + esc(id) +
            '">Open configuration</button></div>';
        }).join("") + "</div>") +
      panel("Vendor vs Product Risk",
        '<table><thead><tr><th></th><th>Severity</th><th>Likelihood</th><th>Risk</th></tr></thead><tbody>' +
        "<tr><th>Vendor</th><td>" + risk(letters.vendor_severity) + "</td><td>" + risk(letters.vendor_likelihood) +
        "</td><td>" + risk(letters.vendor_risk) + "</td></tr>" +
        "<tr><th>Product</th><td>" + risk(letters.product_severity) + "</td><td>" + risk(letters.product_likelihood) +
        "</td><td>" + risk(letters.product_risk) + "</td></tr></tbody></table>") +
      panel("Technical Impact", impactBlocks(run, pkg) + citedFileList(run, list)) +
      panel("Test Coverage", testSnippet(run)) +
      panel("Install vs Skip", '<div class="installSkip"><div class="install"><h3>If we install</h3><ul><li>' +
        esc(installSkip[0]) + "</li></ul></div><div class=\"skip\"><h3>If we skip</h3><ul><li>" +
        esc(installSkip[1]) + "</li></ul></div></div>") +
      "</div>";
  }

  function engineerTabs() {
    return '<div class="tabs">' +
      ["Overview", "Impact Analysis", "Affected Configurations", "Test Coverage", "Dependencies", "Release and Evidence", "History"].map(function (name) {
        return '<button class="' + (engineerTab === name ? "active" : "") + '" data-eng-tab="' +
          name + '">' + name + "</button>";
      }).join("") + "</div>";
  }

  function filledScore(cluster, field) {
    if (cluster && cluster.cluster_key) return scoreLabel(cluster[field]);
    return "not in this snapshot";
  }

  function impactPage(run, pkg) {
    var letters = lettersForKb(run, pkg.kb);
    var cluster = letters.cluster || {};
    return engineerHead(run, '<div class="pageHead"><div><h1>Impact Analysis</h1><p>' + esc(pkg.kb) + " · " +
      esc(pkg.title) + (letters.clusters && letters.clusters.length ? " · " + letters.clusters.length + " cluster(s)" : "") +
      "</p></div></div>") +
      panel("Vendor vs Product Risk",
        "<table><tr><th></th><th>Severity</th><th>Likelihood</th><th>Risk</th></tr>" +
        "<tr><th>Vendor</th><td>" + risk(letters.vendor_severity) + "</td><td>" + risk(letters.vendor_likelihood) +
        "</td><td>" + risk(letters.vendor_risk) + "</td></tr>" +
        "<tr><th>Product</th><td>" + risk(letters.product_severity) + "</td><td>" + risk(letters.product_likelihood) +
        "</td><td>" + risk(letters.product_risk) + "</td></tr></table>") +
      panel("Decision Logic", infoRows([
        ["If we install", esc(filledScore(cluster, "install_risk"))],
        ["If we skip", esc(filledScore(cluster, "skip_risk"))],
        ["Compatibility", esc(filledScore(cluster, "compatibility"))],
        ["Required for app", esc(filledScore(cluster, "required_for_app"))],
        ["Recommendation", pkg.include_in_deploy ? "Install" : "Hold / Do not install"],
        ["Action", esc(pkg.action ? actionLabel(pkg.action) : "not in this snapshot")]
      ])) +
      panel("Technical Impact", impactBlocks(run, pkg) + citedFileList(run, letters.clusters || []));
  }

  function affectedPage(run, pkg) {
    var list = lettersForKb(run, pkg.kb).clusters || [];
    var stations = pkg.stations || [];
    return engineerHead(run, '<div class="pageHead"><div><h1>Affected Configurations</h1><p>' + esc(pkg.kb) +
      " is applicable to " + stations.length + " configurations</p></div></div>") +
      panel("Configuration Scope", stations.map(function (id) {
        var label = configLabel(id);
        var profile = stationProfile(run, id);
        var cluster = clusterForStation(list, id);
        var open = selectedConfig === id;
        var osProduct = profile.os_product || (pkg.os_products || []).join(", ");
        var detail = "";
        if (open) {
          detail = '<div class="configDetail"><div class="configDetailBody">' +
            miniGrid([
              ["OS product", osProduct],
              ["OS build", profile.os_build],
              ["Model", profile.model],
              ["Device role", profile.device_role],
              ["Deployment group", profile.deployment_group]
            ]) +
            (cluster
              ? (clusterImpactText(cluster) ? "<p>" + impactHtml(clusterImpactText(cluster)) + "</p>" : "") +
                scoreList(cluster)
              : '<p class="empty">No impact cluster for this configuration.</p>') +
            "</div></div>";
        }
        return '<button class="configRow" data-select-config="' + esc(id) + '"><b>' +
          esc(label) + "</b><span>" + esc(id) + "</span>" + recStatus(pkg) + "</button>" + detail;
      }).join("") || '<p class="empty">No configurations on this KB.</p>');
  }

  function testPage(run, pkg) {
    var tests = (run && run.tests) || {};
    var planned = [];
    ((run && run.findings) || []).forEach(function (item) {
      (item.tests_to_run || []).forEach(function (row) {
        if (planned.indexOf(row) === -1) planned.push(row);
      });
    });
    return engineerHead(run, '<div class="pageHead"><div><h1>Test Coverage</h1><p>' + esc(pkg.kb) +
      " · Host Application Smoke / Regression</p></div></div>") +
      panel("This run", tests.outcome
        ? infoRows([
          ["Filter", esc(tests.filter || "Smoke|Regression")],
          ["Outcome", esc(tests.outcome)],
          ["Passed", esc(String(tests.passed))],
          ["Failed", esc(String(tests.failed))],
          ["Skipped", esc(String(tests.skipped || 0))],
          ["Total", esc(String(tests.total))]
        ])
        : '<p class="empty">not in this snapshot</p>') +
      panel("PDLC tests to run", planned.length
        ? "<ul>" + planned.map(function (row) { return "<li>" + esc(row) + "</li>"; }).join("") + "</ul>"
        : '<p class="empty">No PDLC test ids in this snapshot.</p>') +
      panel("Findings in this snapshot", ((run && run.findings) || []).length
        ? ((run && run.findings) || []).map(function (item) {
          return '<div class="metricLine"><b>' + esc(item.id) + "</b><span>" +
            esc(item.countermeasure || "—") + " · " + esc(item.title || "") + "</span></div>";
        }).join("")
        : '<p class="empty">No PDLC findings on this run.</p>');
  }

  function dependenciesPage(run) {
    var keys = clusterKeyCounts(run);
    var advice = (run && run.os_kb_advice) || [];
    var osProducts = uniqueStrings(packages(run).reduce(function (all, pkg) {
      return all.concat(pkg.os_products || []);
    }, []).concat(stationProfiles(run).map(function (item) { return item.os_product; })));
    var groups = uniqueStrings(packages(run).reduce(function (all, pkg) {
      return all.concat(pkg.deployment_groups || []);
    }, []).concat(stationProfiles(run).map(function (item) { return item.deployment_group; })));
    return engineerHead(run, '<div class="pageHead"><div><h1>Dependencies</h1><p>Host Application and host KB coupling</p></div></div>') +
      panel("Links", infoRows([
        ["Product", esc(displayProduct(run))],
        ["Branch", esc(run.branch || "main")],
        ["Host Application SHA", run.sha_url ? link(run.sha_url, run.sha) : esc(run.sha || "—")],
        ["FindUpdates run", run.findupdates_url ? link(run.findupdates_url, run.findupdates_run_id) : esc(run.findupdates_run_id || "—")],
        ["Orchestrator run", run.run_url ? link(run.run_url, run.run_id) : esc(run.run_id || "—")]
      ])) +
      panel("Host OS products", osProducts.length
        ? "<ul>" + osProducts.map(function (row) { return "<li>" + esc(row) + "</li>"; }).join("") + "</ul>"
        : '<p class="empty">No OS product names in this snapshot.</p>') +
      panel("Deployment groups", groups.length
        ? "<ul>" + groups.map(function (row) { return "<li>" + esc(row) + "</li>"; }).join("") + "</ul>"
        : '<p class="empty">No deployment groups in this snapshot.</p>') +
      panel("Impact cluster keys", keys.length
        ? keys.map(function (row) {
          return '<div class="metricLine"><b>' + esc(clusterKeyLabel(row.label)) + "</b><span>" + row.value + " clusters</span></div>";
        }).join("")
        : '<p class="empty">No cluster keys on this run.</p>') +
      panel("Host KB advice", advice.length
        ? "<ul>" + advice.map(function (row) { return "<li>" + esc(row) + "</li>"; }).join("") + "</ul>"
        : '<p class="empty">No os_kb_advice in this snapshot.</p>');
  }

  function releaseEvidencePage(run, pkg) {
    var bundle = (run && run.bundle) || {};
    var tests = (run && run.tests) || {};
    var release = (run && run.release) || {};
    var findings = (run && run.findings) || [];
    var evidenceN = findings.filter(function (item) { return String(item.evidence || "").trim(); }).length;
    var checks = [
      ["Bundle", Boolean(bundle.bundle_id), bundle.bundle_id || "missing"],
      ["Host Application zip", Boolean(release.zip_name), release.zip_name || "missing"],
      ["SHA", Boolean(run.sha), run.sha || "missing"],
      ["Tests outcome", Boolean(tests.outcome), tests.outcome || "missing"],
      ["Findings evidence", evidenceN > 0, evidenceN + "/" + findings.length]
    ];
    return engineerHead(run, '<div class="pageHead"><div><h1>Release and Evidence</h1><p>' +
      esc(pkg.kb) + " · snapshot artifacts</p></div></div>") +
      panel("Present in this snapshot", '<div class="timeline">' + checks.map(function (row) {
        return '<div class="timelineItem"><div class="dot ' + (row[1] ? "done" : "pending") +
          '"></div><div>' + esc(row[0]) + "</div><div>" + esc(String(row[2])) + "</div></div>";
      }).join("") + "</div>") +
      panel("Bundle", bundle.bundle_id
        ? infoRows([
          ["Bundle", esc(bundle.bundle_id)],
          ["Generated", esc(bundle.generated || "—")],
          ["FindUpdates", bundle.findupdates_html_url
            ? link(bundle.findupdates_html_url, bundle.findupdates_run_id)
            : esc(run.findupdates_run_id || "—")]
        ])
        : '<p class="empty">No Windows patch bundle on this run.</p>') +
      panel("Host Application zip", release.zip_name
        ? infoRows([
          ["Zip", esc(release.zip_name)],
          ["SHA", run.sha_url ? link(run.sha_url, run.sha) : esc(run.sha || "—")]
        ])
        : '<p class="empty">No application zip on this run.</p>') +
      panel("Tests", tests.outcome
        ? infoRows([
          ["Filter", esc(tests.filter || "—")],
          ["Outcome", esc(tests.outcome)],
          ["Passed", esc(String(tests.passed))],
          ["Failed", esc(String(tests.failed))],
          ["Total", esc(String(tests.total))]
        ])
        : '<p class="empty">not in this snapshot</p>') +
      panel("Finding evidence", findings.length
        ? findings.map(function (item) {
          return '<div class="tech"><b>' + esc(item.id) + " · " + esc(item.countermeasure || "—") +
            "</b><p>" + esc(item.title || "") + "</p>" +
            (item.evidence ? "<p>" + esc(item.evidence) + "</p>" : "") +
            (item.patch_plan && item.patch_plan !== "none" ? "<p>" + esc(item.patch_plan) + "</p>" : "") +
            "</div>";
        }).join("")
        : '<p class="empty">No PDLC findings on this run.</p>');
  }

  function historyPage(run, pkg) {
    var bundle = (run && run.bundle) || {};
    var kb = pkg && pkg.kb;
    var rows = allSnapshots().map(function (item) {
      var found = uniqueKbMap(packages(item))[kb] || null;
      return {
        run_id: item.run_id,
        created_at: item.created_at,
        conclusion: item.conclusion,
        findupdates: item.findupdates_run_id,
        findupdates_url: item.findupdates_url,
        run_url: item.run_url,
        found: found
      };
    });
    return engineerHead(run, '<div class="pageHead"><div><h1>Patch History</h1><p>90-day snapshots for ' +
      esc(kb || "this KB") + "</p></div></div>") +
      panel("This run", infoRows([
        ["Created", esc(run.created_at)],
        ["Workflow", esc(run.workflow || "—")],
        ["Conclusion", esc(run.conclusion || "—")],
        ["Orchestrator run", run.run_url ? link(run.run_url, run.run_id) : esc(run.run_id)],
        ["FindUpdates run", run.findupdates_url ? link(run.findupdates_url, run.findupdates_run_id) : esc(run.findupdates_run_id || "—")],
        ["Host Application SHA", run.sha_url ? link(run.sha_url, run.sha) : esc(run.sha || "—")],
        ["Bundle", esc(bundle.bundle_id || "not in this snapshot")],
        ["Action", esc(actionLabel((pkg && pkg.action) || ""))],
        ["Analysis", esc(formatAiUsage(run.ai))]
      ])) +
      panel("This KB across loaded runs", rows.length
        ? '<div class="timeline">' + rows.map(function (row) {
          var found = row.found;
          var cls = found ? (found.include_in_deploy ? "done" : "") : "pending";
          var rec = found ? (found.include_in_deploy ? "Install" : "Hold / Do not install") : "not in this run";
          var fu = row.findupdates_url
            ? link(row.findupdates_url, row.findupdates || "FindUpdates")
            : esc(row.findupdates || "—");
          var runLink = row.run_url ? link(row.run_url, row.run_id) : esc(row.run_id);
          return '<div class="timelineItem"><div class="dot ' + cls + '"></div><div>' +
            esc(String(row.created_at || "").replace("T", " ")) +
            "<small>" + runLink + "</small></div><div>" +
            esc(row.conclusion || "—") + " · FindUpdates " + fu + " · " + esc(rec) +
            (found && found.action ? " · " + esc(found.action) : "") +
            "</div></div>";
        }).join("") + "</div>"
        : '<p class="empty">History will grow with later runs.</p>');
  }

  function engineerPage(run) {
    var pkg = findPackage(run, selectedKb);
    if (!pkg) return engineerOverview(run, pkg);
    if (engineerTab === "Impact Analysis") return impactPage(run, pkg);
    if (engineerTab === "Affected Configurations") return affectedPage(run, pkg);
    if (engineerTab === "Test Coverage") return testPage(run, pkg);
    if (engineerTab === "Dependencies") return dependenciesPage(run);
    if (engineerTab === "Release and Evidence") return releaseEvidencePage(run, pkg);
    if (engineerTab === "History") return historyPage(run, pkg);
    return engineerOverview(run, pkg);
  }

  function patchList(run) {
    return '<div class="pageHead"><div><h1>Patches</h1><p>All patch findings for this run</p></div></div>' +
      filtersBar(run) + panel(filteredPackages(run).length + " patches matching current filters",
        patchTable(run, filteredPackages(run)));
  }

  function releases(run) {
    var bundle = (run && run.bundle) || {};
    var tests = (run && run.tests) || {};
    var release = (run && run.release) || {};
    var counts = uniqueCounts(run);
    var rows = uniquePackages(run);
    return '<div class="pageHead"><div><h1>Releases</h1><p>Bundle, Host Application zip, and tests from this snapshot</p></div></div>' +
      (bundle.bundle_id
        ? '<div class="releaseHeader"><div><b>' + esc(bundle.bundle_id) + "</b><span>" +
          esc(bundle.generated || "") + "</span></div></div>" +
          miniGrid([
            ["Bundle date", bundle.generated],
            ["Config", String(stationCount(bundle))],
            ["Recommended", String(counts.recommended)],
            ["Held", String(counts.held)]
          ])
        : "") +
      panel("Windows patch bundle", bundle.bundle_id
        ? infoRows([
          ["Bundle", esc(bundle.bundle_id)],
          ["Generated", esc(bundle.generated || "—")],
          ["Recommended", String(counts.recommended)],
          ["Held", String(counts.held)],
          ["Config", String(stationCount(bundle))],
          ["FindUpdates", bundle.findupdates_html_url ? link(bundle.findupdates_html_url, bundle.findupdates_run_id) : esc(run.findupdates_run_id || "—")],
          ["Workflow", esc(run.workflow || "—")],
          ["Conclusion", esc(run.conclusion || "—")],
          ["Artifacts", "KB manifest + APPLY.ps1"]
        ])
        : '<p class="empty">No Windows patch bundle on this run.</p>') +
      panel("Included KBs", rows.length
        ? rows.map(function (pkg) {
          return '<div class="kbLine"><button class="link" data-open-kb="' + esc(pkg.kb) + '">' +
            esc(pkg.kb) + "</button><span class=\"cves\">" +
            esc((pkg.cve_ids || []).join(", ") || pkg.title || "") +
            "</span><span class=\"kbSev\">" + badgeSev(pkg.severity) +
            "</span><span class=\"kbRec\">" + recStatus(pkg) + "</span></div>";
        }).join("")
        : '<p class="empty">No packages on this run.</p>') +
      panel("Host Application package", release.zip_name
        ? infoRows([
          ["Zip", esc(release.zip_name)],
          ["SHA", run.sha_url ? link(run.sha_url, run.sha) : esc(run.sha || "—")]
        ])
        : '<p class="empty">No application zip on this run.</p>') +
      panel("Tests", tests.outcome
        ? infoRows([["Filter", esc(tests.filter || "—")], ["Outcome", esc(tests.outcome)], ["Passed", esc(String(tests.passed))], ["Failed", esc(String(tests.failed))], ["Total", esc(String(tests.total))]])
        : '<p class="empty">not in this snapshot</p>');
  }

  function configurations(run) {
    var names = Object.keys(pageConfigMap).sort();
    if (!names.length) return '<div class="pageHead"><div><h1>Configurations</h1></div></div><p class="empty">No configurations on this run.</p>';
    var selected = selectedConfig && pageConfigMap[selectedConfig] ? selectedConfig : names[0];
    var html = '<div class="pageHead"><div><h1>Configurations</h1><p>Approved lab configurations and patch applicability</p></div></div>';
    names.forEach(function (id) {
      var label = pageConfigMap[id];
      var rows = uniquePackages(run).filter(function (pkg) {
        return labeledStations(pkg.stations).indexOf(label) !== -1;
      });
      html += '<button class="configRow" data-select-config="' + esc(id) + '"><b>' +
        esc(label) + "</b><span>" + esc(id) + " · " + rows.length + " patches</span></button>";
    });
    var profile = stationProfile(run, selected);
    var selectedRows = uniquePackages(run).filter(function (pkg) {
      return labeledStations(pkg.stations).indexOf(pageConfigMap[selected]) !== -1;
    });
    html += panel(pageConfigMap[selected],
      miniGrid([
        ["OS product", profile.os_product],
        ["OS build", profile.os_build],
        ["Model", profile.model],
        ["Device role", profile.device_role],
        ["Deployment group", profile.deployment_group]
      ]) +
      (selectedRows.length
        ? selectedRows.map(function (pkg) {
          return '<div class="metricLine"><button class="link" data-open-kb="' + esc(pkg.kb) + '">' +
            esc(pkg.kb) + "</button>" + badgeSev(pkg.severity) + recStatus(pkg) + "</div>";
        }).join("")
        : '<p class="empty">No patches for this configuration.</p>'));
    return html;
  }

  function reports(run) {
    var findings = (run && run.findings) || [];
    return '<div class="pageHead"><div><h1>Reports</h1><p>Product PDLC findings from this snapshot</p></div></div>' +
      (findings.length
        ? findings.map(function (item) {
          var rows = [];
          if (item.patch_plan && item.patch_plan !== "none") rows.push(["Patch plan", esc(item.patch_plan)]);
          if ((item.impact_files || []).length) rows.push(["Cited files", esc(item.impact_files.join(", "))]);
          if ((item.tests_to_run || []).length) rows.push(["Tests", esc(item.tests_to_run.join(", "))]);
          return panel(esc(item.id) + " · " + esc(item.countermeasure || "—"),
            "<p><b>" + esc(item.title) + "</b></p>" +
            (item.evidence ? "<p>" + esc(item.evidence) + "</p>" : "") +
            (rows.length ? infoRows(rows) : ""));
        }).join("")
        : '<p class="empty">No PDLC findings on this run.</p>');
  }

  function normalizeQuestion(text) {
    return String(text || "").toLowerCase().replace(/[^a-z0-9\s]/g, " ").replace(/\s+/g, " ").trim();
  }

  var QA_OUT = "This question is outside the scope of this report.";
  var QA_EMPTY = "Type a question about this report.";
  var QA_OFF = ["windchill", "password", "bitcoin", "weather", "recipe"];
  var QA_ITEMS = [
    {
      q: "What are PDLC findings?",
      needles: ["pdlc findings", "pdlc finding", "pdlc", "findings"],
      answer: "PDLC findings is the count of Host Application product findings scored in this run. It comes from the product vulnerability report plus code on main. It is not a Windows KB count."
    },
    {
      q: "What are Product findings?",
      needles: ["product findings", "product finding", "present absent partial"],
      answer: "Product findings is the same list as PDLC findings, split by whether a countermeasure is on main: present (defense is in the product), absent (no defense), or partial (only part of the defense is there)."
    },
    {
      q: "What is present, absent, or partial?",
      needles: ["present", "absent", "partial", "countermeasure"],
      answer: "Those labels are for product findings, not KBs. Present means the defense is in Host Application on main. Absent means it is not. Partial means it is only partly there."
    },
    {
      q: "What does Action mean?",
      needles: ["candidate for validation", "candidate_for_validation", "action", "do not install", "do_not_install", "not in scope", "not_in_scope"],
      answer: "Action is the FindUpdates catalogue verdict for that KB. Recommended to validate means the KB is a candidate to test on the lab configuration. Do not install means hold it. Not in scope means this product path does not use that update. This page does not authorize install."
    },
    {
      q: "What is Install vs Hold?",
      needles: ["install", "hold", "recommended to install", "do not install"],
      answer: "Install and Hold come from include_in_deploy on this run. Install means recommended for the lab configuration. Hold means do not install. HOLD and BLOCK from FindUpdates stay. The page is advisory only."
    },
    {
      q: "What is Config1?",
      needles: ["config1", "config 1", "config2", "numbered config"],
      answer: "Config1, Config2, and so on are numbered lab configurations, sorted from the station list in the snapshot. They are not production site names. The same order is used on the chart, matrix, and vendor-impact mail."
    },
    {
      q: "What is vendor vs product risk?",
      needles: ["vendor", "product risk", "letter", "c h m l", "psirt"],
      answer: "Vendor letters are Microsoft / FindUpdates severity and exploitability (KEV is C). Product letters are for Host Application on that configuration. Product risk can be L even when vendor risk is C if the app does not load that component. NA means the KB does not apply to that configuration."
    },
    {
      q: "What does NA mean?",
      needles: ["na", "not applicable"],
      answer: "NA on the KB × Config grid means this KB is not applicable to that configuration in this snapshot."
    },
    {
      q: "What is KEV?",
      needles: ["kev", "known exploited", "known_exploited"],
      answer: "KEV means Known Exploited Vulnerability. If it is true, vendor likelihood is scored C. It is a vendor catalogue fact, not an install authorization."
    },
    {
      q: "Can I install from this page?",
      needles: ["can i install", "authorize", "approval", "deploy"],
      answer: "No. This GitHub Page is advisory only. It cannot start Orchestrator and it is not an authorization to install, approve, or deploy. HOLD and BLOCK stay."
    },
    {
      q: "What is Manager vs Engineer view?",
      needles: ["manager", "engineer"],
      answer: "Manager view is the executive dashboard: KPIs, configuration bars, findings, and latest KBs. Engineer view opens the KB card: impact, configs, tests, evidence, and history."
    },
    {
      q: "What is the stepper?",
      needles: ["stepper", "packages", "impact clusters", "findings or zip"],
      answer: "The stepper only shows whether this snapshot has packages, impact clusters, tests, and findings or a zip. Done means the artifact is in the snapshot. It is not an approval or release gate."
    },
    {
      q: "What is Host Application?",
      needles: ["host application", "hostapplication"],
      answer: "Host Application is the Windows product under test. GitHub repo, exe, and zip use HostApplication. A host OS KB does not patch the self-contained runtime inside the zip."
    },
    {
      q: "What is the bundle?",
      needles: ["bundle", "zip", "apply.ps1"],
      answer: "The Windows patch bundle is a lab artifact: KB manifest and APPLY.ps1, not .msu files. The Host Application zip is the product package from this run, with SHA from main."
    },
    {
      q: "What are tests on this page?",
      needles: ["test coverage", "smoke", "regression"],
      answer: "Test Coverage is Host Application Smoke and Regression from this snapshot, plus PDLC tests_to_run ids. A missing outcome means tests were not recorded in this snapshot."
    },
    {
      q: "What is this report?",
      needles: ["this report", "this page", "orchestrator", "github page"],
      answer: "This is the advisory Windows patch report for Host Application lab configurations. It is built from 90-day Orchestrator snapshots: KBs, impact clusters, PDLC findings, tests, and the bundle. It does not install updates."
    },
    {
      q: "What is severity?",
      needles: ["severity", "critical", "high", "medium", "low"],
      answer: "Severity on a KB is the vendor / MSRC rating from FindUpdates. The severity donut counts unique KBs in this run. It is not the product letter score."
    },
    {
      q: "What is an impact cluster?",
      needles: ["impact cluster", "cluster key", "schannel"],
      answer: "An impact cluster groups how a KB couples to Host Application on a configuration (for example Schannel / TLS). The engineer card shows that impact text and install vs skip scores."
    },
    {
      q: "What do the KPI numbers mean?",
      needles: ["kpi", "runs", "applicable", "held"],
      answer: "Runs is how many Orchestrator snapshots are in the last 90 days. Applicable is unique KBs in this run. Recommended to install and Held are unique KBs by include_in_deploy. PDLC findings is the product-finding count."
    }
  ];

  function answerReportQuestion(raw) {
    var original = String(raw || "").trim();
    var q = normalizeQuestion(original);
    if (!q) return { ok: false, text: QA_EMPTY };
    if (/[а-яё]/i.test(original)) return { ok: false, text: QA_OUT };
    var blocked = false;
    QA_OFF.forEach(function (word) {
      if (q.indexOf(word) !== -1) blocked = true;
    });
    if (blocked) return { ok: false, text: QA_OUT };
    var best = null;
    var bestScore = 0;
    QA_ITEMS.forEach(function (item) {
      var score = 0;
      (item.needles || []).forEach(function (needle) {
        var bit = normalizeQuestion(needle);
        if (bit && q.indexOf(bit) !== -1) score += bit.split(" ").length;
      });
      if (score > bestScore) {
        bestScore = score;
        best = item;
      }
    });
    if (!best || bestScore < 1) return { ok: false, text: QA_OUT };
    return { ok: true, title: best.q, text: best.answer };
  }

  function qaPage() {
    var result = qaQuestion ? answerReportQuestion(qaQuestion) : null;
    var chips = [
      "What are PDLC findings?",
      "What are Product findings?",
      "What does Action mean?",
      "What is Install vs Hold?",
      "What is Config1?",
      "What is vendor vs product risk?",
      "Can I install from this page?"
    ];
    var answerHtml = '<p class="empty">Ask a term you see on this report.</p>';
    if (result) {
      answerHtml = '<div class="qaResult ' + (result.ok ? "ok" : "out") + '">' +
        (result.title && result.ok ? "<b>" + esc(result.title) + "</b>" : "") +
        "<p>" + esc(result.text) + "</p></div>";
    }
    return '<div class="pageHead"><div><h1>Q&amp;A</h1><p>Short answers for labels on this advisory report</p></div></div>' +
      panel("Ask this report",
        '<form id="qa-form" class="qaForm"><input id="qa-input" placeholder="Ask about a label on this report" value="' +
        esc(qaQuestion) + '"><button class="view" type="submit">Ask</button></form>' +
        '<div class="qaChips">' + chips.map(function (item) {
          return '<button class="secondary" type="button" data-qa-ask="' + esc(item) + '">' + esc(item) + "</button>";
        }).join("") + "</div>") +
      panel("Answer", answerHtml);
  }

  function settingsPage() {
    return '<div class="pageHead"><div><h1>Settings</h1><p>Advisory GitHub Page</p></div></div>' +
      panel("Scope", infoRows([
        ["Role", "This page cannot start Orchestrator"],
        ["Data", "90-day snapshots from build-pages-site.py"],
        ["Authorization", "HOLD and BLOCK stay"]
      ]));
  }

  function navItems() {
    if (role === "manager") {
      return ["Dashboard", "Patches", "Releases", "Devices & Configurations", "Reports", "Q&A", "Settings"];
    }
    return ["Dashboard", "Patches", "Releases", "Impact Analysis", "Test Coverage", "Dependencies", "Reports", "Q&A", "Settings"];
  }

  function header(run) {
    var created = String((run && run.created_at) || "").replace("T", " ").replace("Z", "Z");
    var runId = (run && run.run_id) || "";
    var opts = (index.runs || []).map(function (row) {
      return '<option value="' + esc(row.run_id) + '"' +
        (String(row.run_id) === String(runId) ? " selected" : "") +
        ">" + esc(row.label || row.run_id) + "</option>";
    }).join("");
    return '<header class="topbar"><div class="brand"><div class="alcon">Alcon</div>' +
      '<div class="product">Windows Patch Management</div></div>' +
      '<div class="roleSwitch"><button class="' + (role === "manager" ? "active" : "") +
      '" data-role="manager">Manager View</button><button class="' +
      (role === "engineer" ? "active" : "") + '" data-role="engineer">Engineer View</button></div>' +
      '<div class="runMeta"><div><b>Last run: ' + esc(created) + "</b><small>Orchestrator #" +
      esc(runId) + '</small></div><select id="run-select">' + opts + "</select></div></header>";
  }

  function sidebar() {
    var current = page;
    if (role === "engineer" && page === "Patches" && selectedKb) current = "Patches";
    return '<aside class="sidebar">' + navItems().map(function (name) {
      var selected = current === name || (name === "Dashboard" && page === "Dashboard" && role === "manager");
      if (role === "engineer" && page === "Dashboard") selected = name === "Dashboard";
      return '<button class="nav' + (page === name ? " selected" : "") + '" data-page="' +
        name + '">' + name + "</button>";
    }).join("") + "</aside>";
  }

  function content(run) {
    if (page === "Dashboard") return role === "manager" ? managerDashboard(run) : engineerPage(run);
    if (page === "Patches") return role === "engineer" && selectedKb ? engineerPage(run) : patchList(run);
    if (page === "Releases") return releases(run);
    if (page === "Devices & Configurations") return configurations(run);
    if (page === "Impact Analysis") return engineerPage(run);
    if (page === "Test Coverage") return engineerPage(run);
    if (page === "Dependencies") return engineerPage(run);
    if (page === "Reports") return reports(run);
    if (page === "Q&A") return qaPage();
    if (page === "Settings") return settingsPage();
    return managerDashboard(run);
  }

  function bind(run) {
    var roleBtns = shell.querySelectorAll("[data-role]");
    roleBtns.forEach(function (btn) {
      btn.addEventListener("click", function () {
        role = btn.getAttribute("data-role");
        page = "Dashboard";
        engineerTab = "Overview";
        paint(run);
      });
    });
    shell.querySelectorAll("[data-page]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        page = btn.getAttribute("data-page");
        if (page === "Impact Analysis" || page === "Test Coverage" || page === "Dependencies") {
          role = "engineer";
          engineerTab = page === "Impact Analysis" ? "Impact Analysis"
            : page === "Test Coverage" ? "Test Coverage" : "Dependencies";
          if (!selectedKb) {
            var first = uniquePackages(run)[0];
            selectedKb = first ? first.kb : "";
          }
        }
        paint(run);
      });
    });
    shell.querySelectorAll("[data-open-kb]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        selectedKb = btn.getAttribute("data-open-kb");
        role = "engineer";
        page = "Patches";
        engineerTab = "Overview";
        paint(run);
      });
    });
    shell.querySelectorAll("[data-eng-tab]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        engineerTab = btn.getAttribute("data-eng-tab");
        role = "engineer";
        page = "Patches";
        paint(run);
      });
    });
    shell.querySelectorAll("[data-view-all], [data-all-patches]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        page = "Patches";
        selectedKb = "";
        engineerTab = "Overview";
        paint(run);
      });
    });
    shell.querySelectorAll("[data-open-config]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        selectedConfig = btn.getAttribute("data-open-config") || "";
        role = "engineer";
        page = "Patches";
        engineerTab = "Affected Configurations";
        paint(run);
      });
    });
    shell.querySelectorAll("[data-select-config]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        selectedConfig = btn.getAttribute("data-select-config") || "";
        paint(run);
      });
    });
    var search = document.getElementById("kb-search");
    if (search) {
      search.value = query;
      search.addEventListener("input", function () {
        query = search.value;
        paint(run);
        var again = document.getElementById("kb-search");
        if (again) {
          again.focus();
          var len = again.value.length;
          again.setSelectionRange(len, len);
        }
      });
    }
    var cfg = document.getElementById("config-filter");
    if (cfg) {
      cfg.addEventListener("change", function () {
        config = cfg.value;
        paint(run);
      });
    }
    var sev = document.getElementById("severity-filter");
    if (sev) {
      sev.addEventListener("change", function () {
        severity = sev.value;
        paint(run);
      });
    }
    var select = document.getElementById("run-select");
    if (select) {
      select.addEventListener("change", function () { show(select.value); });
    }
    var qaForm = document.getElementById("qa-form");
    if (qaForm) {
      qaForm.addEventListener("submit", function (ev) {
        ev.preventDefault();
        var input = document.getElementById("qa-input");
        qaQuestion = input ? input.value : "";
        paint(run);
        var again = document.getElementById("qa-input");
        if (again) again.focus();
      });
    }
    shell.querySelectorAll("[data-qa-ask]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        qaQuestion = btn.getAttribute("data-qa-ask") || "";
        page = "Q&A";
        paint(run);
        var again = document.getElementById("qa-input");
        if (again) again.focus();
      });
    });
  }

  function paint(run) {
    currentRun = run;
    if (!run) {
      shell.innerHTML = '<p class="empty">No snapshot for this run.</p>';
      updateFooter(null);
      return;
    }
    pageConfigMap = configNameMap(packages(run));
    shell.innerHTML = header(run) + '<div class="body">' + sidebar() + '<main class="main">' +
      content(run) + "</main></div>";
    bind(run);
    updateFooter(run);
  }

  function show(runId) {
    var snap = snapshots[runId] || snapshots[String(runId)];
    if (snap) {
      paint(snap);
      return;
    }
    fetch("data/history/" + encodeURIComponent(runId) + ".json")
      .then(function (res) { return res.ok ? res.json() : null; })
      .then(paint)
      .catch(function () { paint(null); });
  }

  show(index.latest || (index.runs[0] && index.runs[0].run_id));
})();
